#!/bin/sh
# -*- coding: utf-8 -*-
# vim:fileencoding=utf-8
# @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
# @brief Coverage tests and debugging
# @copyright LGPLv3
# @version 2016.03.22


# Check for needed utilities
if ! which gcc > /dev/null; then
    echo "gcc was not found!"
    exit 1
fi
if ! which ezwin > /dev/null; then
    echo "ezwin was not found!"
    exit 1
fi
if ! which gcov > /dev/null; then
    echo "gcov was not found!"
    exit 1
fi
if ! which lcov > /dev/null; then
    echo "lcov was not found!"
    exit 1
fi
if ! which genhtml > /dev/null; then
    echo "genhtml was not found!"
    exit 1
fi
if ! which gdb > /dev/null; then
    echo "gdb was not found!"
    exit 1
fi


# "$1" = Directory path
# "$2" = File-name without extension

# Compile program for coverage tests
echo "======  *COMPILE WITH COVERAGE*  ======"
gcc -I. -L. -fprofile-arcs -ftest-coverage --coverage ./"$2".c -o ./"$2"
# Ask user for an argument for the program (if needed)
INPUT=$(ezwin --text "Type arguments and/or parameters that a user would normally give the program. This is needed for coverage-testing. Press \"Enter\" when finished. Leave the text-box blank if no arguments are desired.")
./"$2" "$INPUT"
# Create FILE.gcov
echo "======  *GCOV*  ======"
gcov --display-progress --demangled-names --all-blocks --function-summaries --unconditional-branches --branch-probabilities ./"$2".c
gcov --object-file ./"$2".gcda --intermediate-format ./"$2".c
# Generate visual test results
mkdir ./Results_\("$2"\)
echo "======  *LCOV AND GENHTML*  ======"
lcov --quiet --test-name "Test_Results" --output-file ./Results_\("$2"\)/Test_Results_\("$2"\).info -c -d ./
genhtml --quiet --show-details --keep-descriptions --function-coverage --branch-coverage --title "$2" -o ./Results_\("$2"\) ./Results_\("$2"\)/Test_Results_\("$2"\).info


# Compile program for debugging
echo "======  *DEBUGGING (GDB)*  ======"
gcc -I. -L. -Q -fmem-report -fsanitize=address -fsanitize=undefined -g3 -ggdb3 ./"$2".c -o ./"$2".gdb
gdb -q ./"$2".gdb


# Display Coverage results in a web-browser
firefox ./Results_\("$2"\)/index.html || chromium ./Results_\("$2"\)/index.html


echo "Completed Testing!"
exit 0
