# PYTHON #


sudo: false
language: python
python:
  - "3.6"
  - "3.7"
install: pip install flake8 pycodestyle pydocstyle pylint tox-travis
script:
  - tox


# C #


language: c
compiler:
  - clang
  - gcc
script:
  - bundle exec rake build
  - bundle exec rake builddoc
deploy:
  skip_cleanup: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq [packages list]
branches:
  only:
    - master
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - gcc-8
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc8"
