.TH FIB 1 "November 03, 2018" "Version: 2018.11.03" "Fibonacci Number Generator"


.SH NAME
fib \- Generate a Fibonacci Number


.SH SYNOPSIS
.B \fBfib\fR \fINUMBER\fR


.SH EXAMPLES
fib 10  # Return the tenth Fibonacci number


.SH SEE ALSO
.BR primesieve (1)


.SH BUGS
Currently, this program is limited to the first 30-37 Fibonacci Numbers (depending on the processor)


.SH AUTHOR
\fBfib\fR was developed by Devyn Collier Johnson <DevynCJohnson@Gmail.com>
.br
This manual page was prepared by Devyn Collier Johnson <DevynCJohnson@Gmail.com>


.SH COPYRIGHT
GNU Lesser General Public License v3

Copyright (c) Devyn Collier Johnson, All rights reserved.

This software is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License along with this software.
