#!/usr/bin/env python3
# -*- coding: utf-8-unix; Mode: Python; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=python syntax=python.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax python; indent-mode python; eol unix; replace-tabs off; indent-width 4; tab-width 4; remove-trailing-space on; line-numbers on;
"""@brief Sort lines (or list) in data stream alphabetically

@file alphabetize_lines
@version 2018.10.13
@author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
@copyright LGPLv3

@section DESCRIPTION
This script can be integrated into Geany to sort selected lines or some single lines.
A single data line (without '\n') can be sorted if it is delimited by '|', ' ', ',', ';', ':', or ', '.
Configure Geany: Edit→Format→Send Selection to→Set Custom Commands

@section LICENSE
GNU Lesser General Public License v3
Copyright (c) Devyn Collier Johnson, All rights reserved.

This software is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This software is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this software.
"""


from sys import argv, stderr, stdin, stdout
from traceback import format_exc
from typing import Callable, List


__all__: list = [
    r'alphadupsort_delimiter_codec',
    r'alphasort_delimiter_codec',
    r'alphabetize_string'
]


def alphadupsort_delimiter_codec(data: str, delimiter: str) -> str:
    """Sort the lines or data-list alphabetically using the specified delimiter and remove duplicates"""
    return delimiter.join(sorted(set(data.split(delimiter)), key=str.lower)).strip()


def alphasort_delimiter_codec(data: str, delimiter: str) -> str:
    """Sort the lines or data-list alphabetically using the specified delimiter"""
    _out: list = data.split(delimiter)
    _out.sort(key=str.lower)
    return delimiter.join(_out).strip()


def alphabetize_string(_data: str, sort_func: Callable[[str, str], str]) -> str:
    """Alphabetize the data separated by a delimiter"""
    _out: List[str] = []
    if not _data or not _data.strip():
        stderr.write('No input provided!\n')
        raise SystemExit(1)
    if '\n' not in _data:
        if r'|' in _data:
            return sort_func(_data, r'|')
        if r', ' in _data:
            return sort_func(_data, r', ')
        if r',' in _data:
            return sort_func(_data, r',')
        if r' ' in _data:
            return sort_func(_data, r' ')
        if r';' in _data:
            return sort_func(_data, r';')
        if r':' in _data:
            return sort_func(_data, r':')
        if '\f' in _data:
            return sort_func(_data, '\f')
    _out = _data.replace('\r\n', '\n').split('\n')
    _out.sort(key=str.lower)
    return '\n'.join(_out)


if __name__ == '__main__':
    HELP: str = 'Usage\n\talphabetize_lines [-r] "string"\n\tcommand | alphabetize_lines [-r]\n' + \
        'Supported Delimters\n\tnewline, formfeed, comma, space, comma+space, `|`, `;`, & `:`\n' + \
        'Optional Parameters\n' + \
        '\t-r: Remove duplicates in addition to sorting\n'
    try:
        RM_DUP: bool = False if len(argv) == 1 else argv[1].lower() in {r'--remove-duplicates', r'--rm-dup', r'-r'}
        SORT_FUNC: Callable[[str, str], str] = alphadupsort_delimiter_codec if RM_DUP else alphasort_delimiter_codec
        if len(argv) == 1 or (RM_DUP and len(argv) == 2):  # Pipe
            DATA: str = stdin.read()
            stdout.write(alphabetize_string(DATA, SORT_FUNC))
        elif argv[1].lower() in {r'help', r'--help', r'-h', r'--usage', r'?'}:  # Help
            stdout.write(HELP)
        elif RM_DUP and len(argv) == 3 and argv[2]:  # Sort & Remove duplicates
            stdout.write(alphabetize_string(argv[2], SORT_FUNC) + '\n')
        elif argv[1]:  # String as argument
            stdout.write(alphabetize_string(argv[1], SORT_FUNC) + '\n')
        else:  # Help
            stdout.write(HELP)
    except SystemExit:
        pass
    except BaseException:
        stderr.write(format_exc() + '\n')
