#!/bin/sh
# -*- coding: utf-8-unix; Mode: Shell; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=shell syn=sh.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax shell; indent-mode normal; eol unix; replace-tabs on; indent-width 4; tab-width 4; remove-trailing-space on;
#' @brief Set the CPU to performance mode
#' @file ampupcpu
#' @version 2019.03.28
#' @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
#' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/


if [ "$(id -u)" != '0' ]; then
    printf '\x1b[1;31mERROR\x1b[0m: Root privileges are required!\n' >&2
    exit 1
elif [ -r /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor ]; then
    for FILE in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
        [ ! -w "$FILE" ] && break
        [ -w "$FILE" ] && echo -n performance > "$FILE"
    done
fi
