#!/usr/bin/env python3
# -*- coding: utf-8-unix; Mode: Python; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=python syntax=python.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax python; indent-mode python; eol unix; replace-tabs off; indent-width 4; tab-width 4; remove-trailing-space on; line-numbers on;
"""@brief Linter and checker for C source code

@file clint
@version 2018.04.27
@author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
@copyright LGPLv3

@section DESCRIPTION
Codes
 - C*** = Comment Warnings & Errors
 - MG** = Magic Comment
 - M*** = Macros Warnings & Errors
 - T000 = Todo Note
 - S*** = Security Issues & Flaws
 - V*** = Vague Code
 - X*** = Inconsistency
 - Z*** = Optimize

@section LICENSE
GNU Lesser General Public License v3
Copyright (c) Devyn Collier Johnson, All rights reserved.

This software is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This software is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this software.
"""


# pylint: disable=C0103


from sys import argv, stderr

try:
    import regex as re  # noqa: E402  # pylint: disable=C0411
except ImportError:
    import re  # noqa: E402  # pylint: disable=C0411


# OBJECTS #


MACROS = r'(define|undef|include|include_next|pragma|error|warning|if|ifdef|ifndef|elif|else|endif|line|import|assert|unassert|ident|sccs)'
ATTRIBUTE_SPECIFIER = r'UNUSED'
ATOMIC = r'(_Atomic|Atomic|atomic|)'
STORAGE_CLASS = r'(auto|extern|register|static|)'
THREAD_STORAGE = r'(thread_local|_Thread_local|)'
QUALIFIER = r'(\*| \*|\* | \* |)(const|restrict|volatile|)(\*| \*|\* | \* |)'
DATATYPES = r'((signed|unsigned|)( |)(short|long|long long||)( |)(int|char|wchar|string|float|double|bool|_BOOL|enum|struct|union|int8_t|uint8_t|int16_t|uint16_t|int32_t|uint32_t|int64_t|uint64_t|FILE|PyObject|)|(ulint|ullint|slint|sllint)(\*| \*|\* | \* |))'
SPECIFIER = ATTRIBUTE_SPECIFIER + ATOMIC + STORAGE_CLASS + ATOMIC + THREAD_STORAGE + QUALIFIER
DATATYPE = SPECIFIER + DATATYPES
ASM_STMT = r'(asm |__asm |__asm__ )(volatile |)'


# PATTERNS #


REGEX_IF_SPACE = re.compile(r'^.+( if\(| if  \(| if\t\().*$')
REGEX_BRACKET_NO_SPACE = re.compile(r'^.+[^ \t]{$')
REGEX_BRACKET_EXTRA_SPACE = re.compile(r'^.+[ \t][ \t]{$')
REGEX_BRACKET_SPACE_VALID = re.compile(r'^.+[ \t]{$')
REGEX_INDENT = re.compile(r'^([ ]+)(.+)$')
REGEX_MUL2 = re.compile(r' = ([^\w]2 \* [\w]+|[\w]+ \* (|\([\w ]+\))2[^[0-9]])')
REGEX_SELF_STORE = re.compile(r'([\w]+) = ([\w]+) ([\w\+\-\*/%\|\^&]+);')
REGEX_SEMICOLON_SPACE = re.compile(r'^.+[ \t]+;$')
REGEX_LICENSE = re.compile(r'^[\w \*]+ __license__ = ".+";$')
REGEX_EMAIL = re.compile(r'^[\w \*]+ __email__ = ".+";$')
REGEX_VALID_EMAIL = re.compile(r'^[\w \*]+ __email__ = "[A-Za-z0-9\-\._]+@[A-Za-z0-9\-]+\.[A-Za-z0-9]+";')
REGEX_DCJ_VERSION = re.compile(r'^[\w \*]+ __version__ = "20[0-9][0-9]\.[0-1][0-9]\.[0-3][0-9]";$')
REGEX_VERSION = re.compile(r'^[\w \*]+ __version__ = (".+"|[0-9\.\-]+);$')

# Magic Comments
REGEX_EMACS = re.compile(r'(//( |)(\-\*\-|)( |)coding( |)(:|=)( |)([\-\w]+)( |)(\-\*\-|))', re.I)
REGEX_EMACS_VALID = re.compile(r'^// \-\*\- coding: utf\-8\-(dos|mac|unix); Mode: C; indent\-tabs\-mode: t; c\-basic\-offset: 4; tab\-width: 4 \-\*\-$')
REGEX_KATE = re.compile(r'(//( |)kate( |):( |)encoding(| |=|= | = | =)([\-\w]+)( ;|;|)(.+|)$)', re.I)
REGEX_KATE_VALID = re.compile(r'^// kate: encoding utf\-8; bom (on|off); syntax c; indent\-mode cstyle; eol (dos|mac|unix); replace-tabs (on|off); indent-width 4; tab-width 4;(|[a-z \-;]+)$')
REGEX_VIM = re.compile(r'(//( |)vim( |):( |)(set |)fileencoding( |)=( |)([\-\w]+)( :|:|))', re.I)
REGEX_VIM_VALID = re.compile(r'^// vim: set fileencoding=utf\-8 filetype=c syntax=c\.doxygen fileformat=(dos|mac|unix) tabstop=4 :$')

# Comments
REGEX_COMMENT_DOC = re.compile(r'^.*/\*\*.*$')  # Beginning of doc-comment
REGEX_COMMENT_MULTILINE_START = re.compile(r'^.*/\*.*$')  # Start of multiline-comment
REGEX_COMMENT_MULTILINE_END = re.compile(r'^.*\*/.*$')  # End of multiline-comment
REGEX_COMMENT_LINE = re.compile(r'^[ \t]*//.+$')  # The entire line is a comment
REGEX_COMMENT_MISSING_LEADING_SPACE = re.compile(r'^.*[^ ]([^ ]|[ ])//.+$')
REGEX_COMMENT_MISSING_SPACE = re.compile(r'//[^ ].+')
REGEX_NOTE = re.compile(r'(//|/\*|/\*\*)( |)(TODO|FIXME|FIX|REPAIR|FINISH|DEBUG|XXX)(:| |$)')

# Datatypes
REGEX_FLOAT = re.compile(r'^' + SPECIFIER + r'float [\w]+( |)=( |)[\+\-]*[0-9]+[XxpA-Fa-f0-9\.\-\+]+(F|);')
REGEX_FLOAT_VALID = re.compile(r'^' + SPECIFIER + r'float [\w]+( |)=( |)[\+\-]*[0-9]+[XxpA-Fa-f0-9\.\-\+]+F;')
REGEX_FLOAT_NUM = re.compile(r'\(float\)( |)[\+\-]*[0-9]+[XxpA-Fa-f0-9\.\-\+]+(F|)[^(A-Za-z\_)+]')
REGEX_FLOAT_NUM_VALID = re.compile(r'\(float\)[\+\-]*[0-9]+[XxpA-Fa-f0-9\.\-\+]+F')
REGEX_LONG_DOUBLE = re.compile(r'^' + SPECIFIER + r'(long double |tetra )[\w]+( |)=( |)[\+\-]*[0-9]+[Xxp0-9A-Fa-f\.\-\+]+(L|);$')
REGEX_LONG_DOUBLE_VALID = re.compile(r'^' + SPECIFIER + r'(long double |tetra )[\w]+ = [\+\-]*[0-9]+[Xxp0-9A-Fa-f\.\-\+]+L;$')
REGEX_LONG_DOUBLE_NUM = re.compile(r'(\(long double\)|\(tetra\))( |)[\+\-]*[0-9]+[Xxp0-9A-Fa-f\.\-\+]+(L|)')
REGEX_LONG_DOUBLE_NUM_VALID = re.compile(r'(\(long double\)|\(tetra\))[\+\-]*[0-9]+[Xxp0-9A-Fa-f\.\-\+]+L')
REGEX_WCHAR = re.compile(r'^' + SPECIFIER + r'wchar_t [\w]+( |)=( |)(L|)\'.+\';$')
REGEX_WCHAR_VALID = re.compile(r'^' + SPECIFIER + r'wchar_t [\w]+ = L\'.+\';$')
REGEX_FLOAT_POINT = re.compile(r'[Xxp0-9A-Fa-f\.\-]+(E|e|)(\+|\-|)[Xxp0-9A-Fa-f]+')

# Macros
REGEX_MACROS = re.compile(r'^[ \t]*#[ \t]*[a-z]+ .+', re.I)
REGEX_MACROS_INDENT = re.compile(r'^#([ ]+).+$')
REGEX_INCLUDE = re.compile(r'^[ \t]*#[ \t]*include[ \t]+(\"|<)[a-z0-9 _\-\./]+(>|\").+', re.I)
REGEX_INCLUDE_VALID = re.compile(r'^#[ ]*include (\"|<)[\w \-\./]+(>|\")(  // .+|)$')
REGEX_MACROS_LEADINGSPACE = re.compile(r'^[ \t]+#[ ]*[a-z]+ .+$')
REGEX_MACROS_SPACE = re.compile(r'^#[ \t]*[a-z]+ [ \t]+.+$')
REGEX_MACROS_VALID = re.compile(r'^#[ ]*[a-z]+ .+$')
REGEX_MACROS_WARN_ERR_SPACE = re.compile(r'^#[ ]*(error|warning)([ ]+)".+"$')
REGEX_OPERATOR_EXTRA_SPACE = re.compile(r'.+(  &&|  \|\||&&  |\|\|  ).+')

# Operators
REGEX_DIV_SPACE = re.compile(r'^.+([ \t]+[ \t]/[^=]|/[^=][ \t][ \t]+).+$')
REGEX_EQUALS_SPACE = re.compile(r'^.+([ \t]+[ \t]=[^=]|=[^=][ \t][ \t]+).+$')
REGEX_MINUS_SPACE = re.compile(r'^.+([ \t]+[ \t]\-[^=]|\-[^=][ \t][ \t]+).+$')
REGEX_MUL_SPACE = re.compile(r'^.+([^, ][ \t]+[ \t]\*[^=]|\*[^=][ \t][ \t]+).+$')
REGEX_NOT_EQUALS_SPACE = re.compile(r'^.+([ \t]+[ \t]\!=|\!=[ \t][ \t]+).+$')
REGEX_PLUS_SPACE = re.compile(r'^.+([ \t]+[ \t]\+[^=]|\+[^=][ \t]+[ \t]).+$')
REGEX_PLUS_EQUALS_SPACE = re.compile(r'^.+([ \t]+[ \t]\+=|\+=[ \t][ \t]+).+$')
REGEX_MINUS_EQUALS_SPACE = re.compile(r'^.+([ \t]+[ \t]\-=|\-=[ \t][ \t]+).+$')
REGEX_MUL_EQUALS_SPACE = re.compile(r'^.+([ \t]+[ \t]\*=|\*=[ \t][ \t]+).+$')
REGEX_DIV_EQUALS_SPACE = re.compile(r'^.+([ \t]+[ \t]/=|/=[ \t][ \t]+).+$')
REGEX_MOD_EQUALS_SPACE = re.compile(r'^.+([ \t]+[ \t]%=|%=[ \t][ \t]+).+$')
REGEX_LSHIFT_EQUALS_SPACE = re.compile(r'^.+([ \t]+[ \t]<<=|<<=[ \t][ \t]+).+$')
REGEX_RSHIFT_EQUALS_SPACE = re.compile(r'^.+([ \t]+[ \t]>>=|>>=[ \t][ \t]+).+$')
REGEX_AND_EQUALS_SPACE = re.compile(r'^.+([ \t]+[ \t]\&=|\&=[ \t][ \t]+).+$')
REGEX_OR_EQUALS_SPACE = re.compile(r'^.+([ \t]+[ \t]\|=|\|=[ \t][ \t]+).+$')
REGEX_XOR_EQUALS_SPACE = re.compile(r'^.+([ \t]+[ \t]\^=|\^=[ \t][ \t]+).+$')
REGEX_MOD_SPACE = re.compile(r'^.+([ \t]+[ \t]%[^=]|%[^=][ \t][ \t]+).+$')
REGEX_AND_SPACE = re.compile(r'^.+([ \t]+[ \t]\&\&|\&\&[ \t][ \t]+).+$')
REGEX_OR_SPACE = re.compile(r'^.+([ \t]+[ \t]\|\||\|\|[ \t][ \t]+).+$')
REGEX_TERNARY_SPACE = re.compile(r'^.+([ \t]+[ \t]\?|\?[ \t][ \t]+).+$')
REGEX_NOT_SPACE = re.compile(r'^.+([ \t]+[ \t]\!|\![ \t]+).+$')
REGEX_LT_SPACE = re.compile(r'^.+[ \t]+[ \t]<.+$')
REGEX_GT_SPACE = re.compile(r'^.+[ \t]+[ \t]>.+$')
REGEX_OPERATOR_NO_SPACE1 = re.compile(r'^.+([\!\+\-\*/%\&\^\|=]=|>=|<=|<<|>>|>>=|<<=|\&\&|\|\|)[^ \t].+$')
REGEX_OPERATOR_NO_SPACE2 = re.compile(r'^.+[^ \t]([\!\+\-\*/%\&\^\|=]=|>=|<=|<<|>>|>>=|<<=|\&\&|\|\|).+$')
OPERATOR_SPACE_VALID = re.compile(r'.+ ([\!\+\-\*/%\&\^\|=]=|>=|<=|<<|>>|>>=|<<=|\&\&|\|\|) .+')
EQUALS_INVALID_SPACE = re.compile(r'.+([\w\)\]\}\t]=|=[\w\(\[\{\t]).+')
EQUALS_SPACE_VALID = re.compile(r'^.+ = .+$')
REGEX_SHIFT_COMPARE = re.compile(r'.+(>=|<=|>>=|<<=).+')
REGEX_SHIFT_COMPARE2 = re.compile(r'.+(>=|<=|>>=|<<=|<<|>>).+')
LTGT_NO_SPACE = re.compile(r'.+([\w\)\]\}]<|<[\w\(\[\{]|[\w\)\]\}]>|>[\w\(\[\{]).+')
LTGT_SPACE_VALID = re.compile(r'^.+ (<|>) .+$')
MATH_OPERATOR_NO_SPACE = re.compile(r'.+([\w\)\]\}](\+|\*|/|%)|(\+|\*|/|%)[\w\(\[\{]).+')  # Subtraction is not included because of negative numbers being mistaken as subtraction
MATH_OPERATOR_SPACE_VALID = re.compile(r'^.+( (\+|/|%) |[^\{&,] \*(restrict| restrict|\}|) ).+$')
MATH_OPERATOR_POINTERS = re.compile(r'[\+\-\*/%\|&<>=\{\}\(,;] (&|\*|\*\*)[\w\(]+')
DATATYPE_PTR = re.compile(r'^[\t]*[\w ]+\*.+$')

# Inline Assembly
REGEX_VALID_ASM = re.compile(ASM_STMT + r'\(.+\);')

# Printf & related functions
PRINTF_FMT = r'''\
(                        # start of capture group 1
%                        # literal "%"
(?:                      # first option
(?:[-+0 #]{0,5})         # optional flags
(?:\d+|\*)?              # width
(?:\.(?:\d+|\*))?        # precision
(?:h|l|ll|w|I|I32|I64)?  # size
[cCdiouxXeEfgGaAnpsSZ]   # type
) |                      # OR
%%)                      # literal "%%"
'''  # noqa: S001

# Security Issues
REGEX_GETC = re.compile(r'[^\w\.]getc\(.+')
REGEX_GETS = re.compile(r'[^\w\.]gets\(.+')
REGEX_MALLOC = re.compile(r'[^\w\.]malloc\(.+')
REGEX_PRINTF = re.compile(r'[^\w\.]printf\(.+')
REGEX_PUTC = re.compile(r'[^\w\.]putc\(.+')
REGEX_PUTS = re.compile(r'[^\w\.]puts\(.+')
REGEX_STRCMP = re.compile(r'[^\w\.]strcmp\(.+')
REGEX_STRCPY = re.compile(r'[^\w\.]strcpy\(.+')


# FUNCTIONS #


def getfile(_filename: str) -> str:
    """Get file contents and return as a str"""
    _out = []
    with open(_filename, mode=r'rt', encoding=r'utf-8') as _file:
        _out.append(r''.join(_file.readlines()).strip())
    return r''.join(_out)


def getfile_list(_filename: str) -> list:
    """Get file contents and return as a list"""
    with open(_filename, mode=r'rt', encoding=r'utf-8') as _file:
        _out = _file.readlines()
    return _out


def output_info(_filepath: str, _linenum: int, _line: str, _code: str, _msg: str, _mstr=r'0') -> None:
    """Display warning/error information on stderr"""
    if _mstr == r'0' and (_line == r'' or _line is None):
        stderr.write(_filepath + r':' + str(_linenum) + r':0: ' + _code + r' : ' + _msg + '\n')
    elif _mstr == r'0':
        stderr.write(_filepath + r':' + str(_linenum) + r':0: ' + _code + r' : ' + _msg + '\n' + _line + '\n')
    elif (_line == r'' or _line is None) and not isinstance(_mstr, str):
        stderr.write(_filepath + r':' + str(_linenum) + r':' + str(_mstr.start()) + r': ' + _code + r' : ' + _msg + '\n')
    elif not isinstance(_mstr, str) and isinstance(_line, str):
        stderr.write(_filepath + r':' + str(_linenum) + r':' + str(_mstr.start()) + r': ' + _code + r' : ' + _msg + '\n' + _line + '\n')
    return None


def strip_strings(_str: str) -> str:
    """Remove all strings"""
    _str = re.sub(r'"[\w \.\+\-\*/%&\|<>!\?\(\):]*"(,|)', r'', _str.strip())
    return re.sub(r'\'[\w \.\+\-\*/%&\|<>!\?\(\):]*\'(,|)', r'', _str)


def strip_comments_and_strings(_str: str) -> str:
    """Remove all comments and strings to produce LOGICAL_LINE/LOG_LINE"""
    _str = strip_strings(_str)
    _str = re.sub(r'(.*)//.*', r'\1', _str)
    return re.sub(r'(.*)/\*.*', r'\1', _str)


# LINT CHECKERS #


# Comment Warnings & Errors

def c000(FILEPATH: str, LINE_NUM: int, LINE: str, LOG_LINE: str) -> None:  # noqa: N803  # pylint: disable=W0613,W0621
    """C***: Check for formatting issues in comments"""
    # C001
    _match = REGEX_COMMENT_MISSING_SPACE.search(LINE)
    if _match and r'://' not in LINE[_match.start():] + LINE[:_match.end()]:
        output_info(FILEPATH, LINE_NUM, LINE, r'C001', r'Missing single space after `//`', _match)
    # C002
    _match = REGEX_COMMENT_MISSING_LEADING_SPACE.search(LINE)
    if _match and r'://' not in LINE[_match.start():] + LINE[:_match.end()]:
        output_info(FILEPATH, LINE_NUM, LINE, r'C002', r'Missing double-leading-space before `//`', _match)
    return None


def c000_line(FILEPATH: str, LINE_NUM: int, LINE: str, LOG_LINE: str) -> None:  # noqa: N803  # pylint: disable=W0613,W0621
    """C***: Check for formatting issues in comment lines"""
    # C000
    _match = REGEX_COMMENT_MISSING_SPACE.search(LINE)
    if _match and r'://' not in LINE[_match.start():] + LINE[:_match.end()]:
        output_info(FILEPATH, LINE_NUM, LINE, r'C000', r'Missing single space after `//` in comment line', _match)
    return None


# Macros Warnings & Errors

def m000(FILEPATH: str, LINE_NUM: int, LINE: str, LOG_LINE: str) -> None:  # noqa: N803  # pylint: disable=W0613,W0621
    """M***: Check for issues in macros code (i.e. formatting, inconsistencies, security, etc.)"""
    # M001
    _match = REGEX_MACROS_LEADINGSPACE.search(LINE)
    if _match:
        output_info(FILEPATH, LINE_NUM, LINE, r'M001', r'Macros should not have leading space', _match)
    # M002
    _match = REGEX_MACROS_VALID.search(LINE)
    if not _match:
        output_info(FILEPATH, LINE_NUM, LINE, r'M002', r'Invalid macros format')
    # M003
    if r'endif  //' not in LINE and r'else  //' not in LINE and r'error   "' not in LINE and r'warning   "' not in LINE:
        _match = REGEX_MACROS_SPACE.search(LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'M003', r'Extra space not needed after macros command', _match)
    # M004
    _match = REGEX_INCLUDE.search(LINE)
    _match2 = REGEX_INCLUDE_VALID.search(LINE)
    if _match and not _match2:
        output_info(FILEPATH, LINE_NUM, LINE, r'M004', r'Invalid format for `#include` macros', _match)
    # M005
    _match = REGEX_OPERATOR_EXTRA_SPACE.search(LINE)
    if _match:
        output_info(FILEPATH, LINE_NUM, LINE, r'M005', r'Extra space is not needed around operators', _match)
    # M006
    _match = REGEX_MACROS_INDENT.search(LINE)
    if _match and (len(_match.group(1)) % 3 != 0):
        output_info(FILEPATH, LINE_NUM, LINE, r'M006', r'Invalid amount of indentation; use one tab per indent level', _match)
    # M007
    _match = REGEX_MACROS_WARN_ERR_SPACE.search(LINE)
    if _match and (len(_match.group(2)) != 3):
        output_info(FILEPATH, LINE_NUM, LINE, r'M007', r'Invalid spacing; use three spaces between error/warning macros and the string', _match)
    return None


# Security Issues & Flaws

def s000(FILEPATH: str, LINE_NUM: int, LINE: str, LOG_LINE: str) -> None:  # noqa: N803  # pylint: disable=W0613,W0621
    """S***: Check for potential security flaws and issues"""
    if r'(' in LOG_LINE and r')' in LOG_LINE and not LOG_LINE.startswith(r'DECL_FUNC') and not LOG_LINE.startswith(r'LIB_FUNC'):
        # S001
        _match = REGEX_GETS.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'S001', r'To strengthen security, use `fgets()` instead of `gets()`', _match)
        # S002
        _match = REGEX_PRINTF.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'S002', r'To strengthen security, use `fprintf()` instead of `printf()`', _match)
        # S003
        _match = REGEX_PUTC.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'S003', r'To strengthen security, use `fputc()` instead of `putc()`', _match)
        # S004
        _match = REGEX_PUTS.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'S004', r'To strengthen security, use `fputs()` instead of `puts()`', _match)
        # S005
        _match = REGEX_MALLOC.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'S005', r'To strengthen security, use `calloc()` instead of `malloc()`', _match)
        # S006
        _match = REGEX_STRCPY.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'S006', r'To strengthen security, use `strncpy()` instead of `strcpy()`', _match)
        # S007
        _match = REGEX_STRCMP.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'S007', r'To strengthen security, use `strncmp()` instead of `strcmp()`', _match)
        # S008
        _match = REGEX_GETC.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'S008', r'To strengthen security, use `fgetc()` instead of `getc()`', _match)
    return None


# "Todo" Note

def t000(FILEPATH: str, LINE_NUM: int, LINE: str, LOG_LINE: str) -> None:  # noqa: N803  # pylint: disable=W0613,W0621
    """T***: Look for "todo" notes"""
    # T000
    _match = REGEX_NOTE.search(LINE)
    if _match:
        output_info(FILEPATH, LINE_NUM, LINE, r'T000', r'Todo note found', _match)
    return None


# Vague Code

def v000(FILEPATH: str, LINE_NUM: int, LINE: str, LOG_LINE: str) -> None:  # noqa: N803  # pylint: disable=W0613,W0621
    """V***: Check for vague code that may perform an unintended action
    Remember, explicit code is better than implicit code
    """
    return None


# Inconsistency

def x000(FILEPATH: str, LINE_NUM: int, LINE: str, LOG_LINE: str) -> None:  # noqa: C901,N803  # pylint: disable=C0103,R0912,R0915,W0613,W0621
    """X***: Check for inconsistencies and bad formatting"""
    if r'__' in LOG_LINE:
        # X001
        _match = REGEX_EMAIL.search(LINE)
        _match2 = REGEX_VALID_EMAIL.search(LINE)
        if _match and not _match2:
            output_info(FILEPATH, LINE_NUM, LINE, r'X001', r'Invalid email format', _match)
        # X002
        _match = REGEX_LICENSE.search(LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X002', r'Use `__copyright__` instead of `__license__`', _match)
        # X003
        _match = REGEX_VERSION.search(LINE)
        _match2 = REGEX_DCJ_VERSION.search(LINE)
        if _match and not _match2:
            output_info(FILEPATH, LINE_NUM, LINE, r'X003', r'Use the format `"YYYY.MM.DD"` with `__version__`', _match)
    # X004
    _match = REGEX_INDENT.search(LINE)
    if _match:
        output_info(FILEPATH, LINE_NUM, LINE, r'X004', r'Invalid indentation white-space; use one tab per indent level', _match)
    # X005: Removed
    if r'long double' in LOG_LINE:
        # X006
        _match = REGEX_LONG_DOUBLE.search(LOG_LINE)
        _match2 = REGEX_LONG_DOUBLE_VALID.search(LOG_LINE)
        _match3 = REGEX_LONG_DOUBLE_NUM.search(LOG_LINE)
        _match4 = REGEX_LONG_DOUBLE_NUM_VALID.search(LOG_LINE)
        if _match and not _match2:
            output_info(FILEPATH, LINE_NUM, LINE, r'X006', r'Missing `L` after the assigned `long double` number', _match)
        elif _match3 and not _match4:
            output_info(FILEPATH, LINE_NUM, LINE, r'X006', r'Missing `L` after the assigned `long double` number', _match3)
    if r'float' in LOG_LINE:
        # X007
        _match = REGEX_FLOAT.search(LOG_LINE)
        _match2 = REGEX_FLOAT_VALID.search(LOG_LINE)
        _match3 = REGEX_FLOAT_NUM.search(LOG_LINE)
        _match4 = REGEX_FLOAT_NUM_VALID.search(LOG_LINE)
        if _match and not _match2:
            output_info(FILEPATH, LINE_NUM, LINE, r'X007', r'Missing `F` after the assigned `float` number', _match)
        elif _match3 and not _match4:
            output_info(FILEPATH, LINE_NUM, LINE, r'X007', r'Missing `F` after the assigned `float` number', _match3)
    if r'wchar_t' in LOG_LINE:
        # X008
        _match = REGEX_WCHAR.search(LINE)
        _match2 = REGEX_WCHAR_VALID.search(LINE)
        if _match and not _match2:
            output_info(FILEPATH, LINE_NUM, LINE, r'X008', r'Missing `L` before the literal wide-character', _match)
    # X009
    _match = REGEX_SEMICOLON_SPACE.search(LOG_LINE)
    if _match and not LINE.strip().endswith(r'";') and not LINE.strip().endswith('\';'):
        output_info(FILEPATH, LINE_NUM, LINE, r'X009', r'No white-space should be before a semi-colon', _match)
    if r'=' in LOG_LINE:
        # X010
        _match = REGEX_EQUALS_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X010', r'Single white-space only around `=`', _match)
        # X011
        _match = REGEX_NOT_EQUALS_SPACE.search(LOG_LINE)
        if _match and ' != \'' not in LINE and '\' != ' not in LINE:
            output_info(FILEPATH, LINE_NUM, LINE, r'X011', r'Single white-space only around `!=`', _match)
    if r'+' in LOG_LINE or r'-' in LOG_LINE or r'/' in LOG_LINE or r'*' in LOG_LINE and not LOG_LINE.startswith(r':'):
        # X012
        _match = REGEX_DIV_SPACE.search(LOG_LINE)
        if _match and ' / \'' not in LINE and '\' / ' not in LINE and r' / "' not in LINE and r'" / ' not in LINE:
            output_info(FILEPATH, LINE_NUM, LINE, r'X012', r'Single white-space only around `/`', _match)
        # X013
        _match = REGEX_MINUS_SPACE.search(LOG_LINE)
        if _match and ' - \'' not in LINE and '\' - ' not in LINE and r' - "' not in LINE and r'" - ' not in LINE:
            output_info(FILEPATH, LINE_NUM, LINE, r'X013', r'Single white-space only around `-`', _match)
        # X014
        _match = REGEX_MUL_SPACE.search(LOG_LINE)
        if _match and r'typedef' not in LOG_LINE and r'*:' not in LOG_LINE:
            output_info(FILEPATH, LINE_NUM, LINE, r'X014', r'Single white-space only around `*`', _match)
        # X015
        _match = REGEX_PLUS_SPACE.search(LOG_LINE)
        if _match and ' + \'' not in LINE and '\' + ' not in LINE and r' + "' not in LINE and r'" + ' not in LINE:
            output_info(FILEPATH, LINE_NUM, LINE, r'X015', r'Single white-space only around `+`', _match)
    if r'=' in LOG_LINE:
        # X016
        _match = REGEX_PLUS_EQUALS_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X016', r'Single white-space only around `+=`', _match)
        # X017
        _match = REGEX_MINUS_EQUALS_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X017', r'Single white-space only around `-=`', _match)
        # X018
        _match = REGEX_MUL_EQUALS_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X018', r'Single white-space only around `*=`', _match)
        # X019
        _match = REGEX_DIV_EQUALS_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X019', r'Single white-space only around `/=`', _match)
        # X020
        _match = REGEX_MOD_EQUALS_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X020', r'Single white-space only around `%=`', _match)
        # X021
        _match = REGEX_LSHIFT_EQUALS_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X021', r'Single white-space only around `<<=`', _match)
        # X022
        _match = REGEX_RSHIFT_EQUALS_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X022', r'Single white-space only around `>>=`', _match)
        # X023
        _match = REGEX_AND_EQUALS_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X023', r'Single white-space only around `&=`', _match)
        # X024
        _match = REGEX_OR_EQUALS_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X024', r'Single white-space only around `^=`', _match)
        # X025
        _match = REGEX_XOR_EQUALS_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X025', r'Single white-space only around `|=`', _match)
    if r'%' in LOG_LINE and not LOG_LINE.startswith(r':'):
        # X026
        _match = REGEX_MOD_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X026', r'Single white-space only around `%`', _match)
    if r'&&' in LOG_LINE and ' && \'' not in LINE and '\' && ' not in LINE and r' && "' not in LINE and r'" && ' not in LINE:
        # X027
        _match = REGEX_AND_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X027', r'Single white-space only around `&&`', _match)
    if r'||' in LOG_LINE and ' || \'' not in LINE and '\' || ' not in LINE and r' || "' not in LINE and r'" || ' not in LINE:
        # X028
        _match = REGEX_OR_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X028', r'Single white-space only around `||`', _match)
    if r'?' in LOG_LINE and ' ? \'' not in LINE and '\' ? ' not in LINE and r' ? "' not in LINE and r'" ? ' not in LINE:
        # X029
        _match = REGEX_TERNARY_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X029', r'Single white-space before and after ternary operator (`?`)', _match)
    if r'!' in LOG_LINE:
        # X030
        _match = REGEX_NOT_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X030', r'Single white-space before `!` and no trailing white-space', _match)
    if r'<' in LOG_LINE and ' < \'' not in LINE and '\' < ' not in LINE and r' <= ' not in LOG_LINE:
        # X031
        _match = REGEX_LT_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X031', r'Single white-space before `<`', _match)
    if r'>' in LOG_LINE and ' > \'' not in LINE and '\' > ' not in LINE and r' >= ' not in LOG_LINE:
        # X032
        _match = REGEX_GT_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X032', r'Single white-space before `>`', _match)
    # X033
    _match = REGEX_OPERATOR_NO_SPACE1.search(LOG_LINE)
    _match2 = REGEX_OPERATOR_NO_SPACE2.search(LOG_LINE)
    _match3 = OPERATOR_SPACE_VALID.search(LOG_LINE)
    if _match and not LOG_LINE.startswith(r':') and not _match3:
        output_info(FILEPATH, LINE_NUM, LINE, r'X033', r'Missing single white-space around operator', _match)
    elif _match2 and not LOG_LINE.startswith(r':') and not _match3:
        output_info(FILEPATH, LINE_NUM, LINE, r'X033', r'Missing single white-space around operator', _match2)
    asm_match = REGEX_VALID_ASM.search(LOG_LINE)
    if r'=' in LOG_LINE and not LOG_LINE.startswith(r':') and not asm_match:
        # X034
        _match = EQUALS_INVALID_SPACE.search(LOG_LINE)
        _match2 = EQUALS_SPACE_VALID.search(LOG_LINE)
        _match3 = REGEX_SHIFT_COMPARE.search(LOG_LINE)
        if _match and not _match2 and not _match3:
            output_info(FILEPATH, LINE_NUM, LINE, r'X034', r'Missing single white-space around `=`', _match)
    if (r'<' in LOG_LINE or '>' in LOG_LINE) and not LOG_LINE.strip().startswith(r'#') and not LOG_LINE.strip().startswith(r'template ') and r'->' not in LOG_LINE:
        # X035
        _match = LTGT_NO_SPACE.search(LOG_LINE)
        _match2 = LTGT_SPACE_VALID.search(LOG_LINE)
        _match3 = REGEX_SHIFT_COMPARE2.search(LOG_LINE)
        if _match and not _match2 and not _match3:
            output_info(FILEPATH, LINE_NUM, LINE, r'X035', r'Missing single white-space around `>` or `<` operator', _match)
    asm_match = REGEX_VALID_ASM.search(LOG_LINE)
    if any(_test in LOG_LINE for _test in [r'+', r'*', r'/', r'%']) and not any(_test in LOG_LINE for _test in [r'++', r'--', r'%', r'<=', r'>=', r'!*', r'!&', r'(*', r'*)', r'return *', r'char* ', r'(int)*']) and not any(LOG_LINE.startswith(_test) for _test in [r'*', r'LIB_FUNC', r'DECL_FUNC']) and not asm_match:
        # X036
        _match = MATH_OPERATOR_NO_SPACE.search(LOG_LINE)
        _match2 = MATH_OPERATOR_SPACE_VALID.search(LOG_LINE)
        _match3 = REGEX_FLOAT_POINT.search(LOG_LINE)
        _match4 = DATATYPE_PTR.search(LOG_LINE)
        _match5 = MATH_OPERATOR_POINTERS.search(LOG_LINE)
        if _match and not _match2 and not _match3 and not _match4 and not _match5:
            output_info(FILEPATH, LINE_NUM, LINE, r'X036', r'Missing single white-space around math operator', _match)
    if r'{' in LOG_LINE:
        # X037
        if LINE.startswith(r'{') and LINE.endswith(r'{'):
            output_info(FILEPATH, LINE_NUM, LINE, r'X037', r'A starting-bracket (`{`) should not start a line')
        # X038
        _match = REGEX_BRACKET_NO_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X038', r'Missing single white-space before bracket', _match)
        # X039
        _match = REGEX_BRACKET_EXTRA_SPACE.search(LOG_LINE)
        if _match:
            output_info(FILEPATH, LINE_NUM, LINE, r'X039', r'Single white-space before bracket, not more than one', _match)
    if r'/*' in NO_STR_LINE and r'*/' in NO_STR_LINE:
        # X040 & X041
        if r'/**' not in NO_STR_LINE and NO_STR_LINE.startswith(r'/*') and NO_STR_LINE.endswith(r'*/'):
            if r'<' not in NO_STR_LINE and NO_STR_LINE.upper() != NO_STR_LINE:
                output_info(FILEPATH, LINE_NUM, LINE, r'X040', r'Section headings (`/* SECTION */`) should not contain lowercase letters')
            if r'/* ' not in NO_STR_LINE or ' */' not in NO_STR_LINE:
                output_info(FILEPATH, LINE_NUM, LINE, r'X041', r'Section headings (`/* SECTION */`) should have a single space on each side of the section name')
    if LINE.endswith(r' ') or LINE.endswith('\t'):
        # X042
        output_info(FILEPATH, LINE_NUM, LINE, r'X042', r'Trailing white-space found')
    if r'for(' in LOG_LINE or r'for  (' in LOG_LINE or 'for\t(' in LOG_LINE:
        # X043
        output_info(FILEPATH, LINE_NUM, LINE, r'X043', r'Single space (never TAB) needed between `for` and `(`')
    if r'while(' in LOG_LINE or r'while  (' in LOG_LINE or 'while\t(' in LOG_LINE:
        # X044
        output_info(FILEPATH, LINE_NUM, LINE, r'X044', r'Single space (never TAB) needed between `while` and `(`')
    _match = REGEX_IF_SPACE.search(LOG_LINE)
    if _match or (LOG_LINE.strip().startswith(r'if') and (r'if(' in LOG_LINE or r'if  (' in LOG_LINE or 'if\t(' in LOG_LINE)):
        # X045
        output_info(FILEPATH, LINE_NUM, LINE, 'X045', 'Single space (never TAB) needed between `if` and `(`')
    if r'switch(' in LOG_LINE or r'switch  (' in LOG_LINE or 'switch\t(' in LOG_LINE:
        # X046
        output_info(FILEPATH, LINE_NUM, LINE, r'X046', r'Single space (never TAB) needed between `switch` and `(`')
    if (r'[]' in LOG_LINE or r'[ ]' in LOG_LINE) and not any(_test in LOG_LINE for _test in [r' main(', r'[];', r'[]);', r'[],', r'[] = {', r' argv[]', r' envp[]']) and not any(LOG_LINE.startswith(_test) for _test in [r'extern', r'UNUSED', r'LIB_FUNC', r'DECL_FUNC']):
        # X047
        output_info(FILEPATH, LINE_NUM, LINE, r'X047', r'Invalid array size')
    if r'return  ' in LOG_LINE or 'return\t' in LOG_LINE:
        # X048
        output_info(FILEPATH, LINE_NUM, LINE, r'X048', r'Unneeded extra white-space after return')
    return None


# Optimize

def z000(FILEPATH: str, LINE_NUM: int, LINE: str, LOG_LINE: str) -> None:  # noqa: N803  # pylint: disable=C0103,W0613,W0621
    """Z***: Check for code that can be optimized and suggest optimal code"""
    if r'i = i + 1;' in LOG_LINE or r'j = j + 1;' in LOG_LINE or r'i = i - 1;' in LOG_LINE or r'j = j - 1;' in LOG_LINE:
        # Z001
        output_info(FILEPATH, LINE_NUM, LINE, r'Z001', r'Use an increment (`++`) or decrement (`--`) instead of code in the formats `x = x + 1` and `x += 1`')
    if r'i += 1;' in LOG_LINE or r'j += 1;' in LOG_LINE or r'i -= 1;' in LOG_LINE or r'j -= 1;' in LOG_LINE:
        # Z001
        output_info(FILEPATH, LINE_NUM, LINE, r'Z001', r'Use an increment (`++`) or decrement (`--`) instead of code in the formats `x = x + 1` and `x += 1`')
    # Z002
    _match = REGEX_SELF_STORE.search(LOG_LINE)
    if _match and _match.group(1) == _match.group(2) and r'.' + _match.group(1) not in LOG_LINE:
        output_info(FILEPATH, LINE_NUM, LINE, r'Z002', r'Re-write code in the format `x = x + 1` to `x += 1`')
    # Z003
    _match = REGEX_MUL2.search(LOG_LINE)
    if _match:
        output_info(FILEPATH, LINE_NUM, LINE, r'Z003', r'Due to the multiplicative properties, `2 * x` is the same as `x + x`, which computers can compute more quickly')
    return None


# MAIN #


if __name__ == '__main__':  # noqa: C901
    # GET SRC #
    if len(argv) == 2:
        try:
            SRC_FILE = getfile(argv[1])
            SRC_FILE_LIST = getfile_list(argv[1])
            FILEPATH = argv[1]
        except PermissionError:
            stderr.write(r'PermissionError!\n')
            raise SystemExit(1)
        except IOError:
            stderr.write(r'IOError!\n')
            raise SystemExit(1)
    else:
        stderr.write(r'Invalid parameters!\n')
        raise SystemExit(1)
    # SET VARIABLES #
    LINE_NUM = 1
    INSIDE_MULTILINE_COMMENT = False
    # ANALYZE SRC #
    for LINE in SRC_FILE_LIST:  # Scan one line at-a-time
        if LINE_NUM is 1:  # MG0*: Magic-Emacs-Comment
            if LINE.startswith(r'#!'):
                output_info(FILEPATH, 1, LINE, r'ERROR', r'This appears to be a script')
                raise SystemExit(1)
            _match = REGEX_EMACS.search(LINE)
            _match2 = REGEX_EMACS_VALID.search(LINE)
            if _match and not _match2:
                output_info(FILEPATH, LINE_NUM, LINE, r'MG01', r'Invalid format for Magic-Emacs-Comment; use `// -*- coding: utf-8-unix; Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-`', _match)
            elif not _match:
                output_info(FILEPATH, LINE_NUM, r'', r'MG02', r'Missing Magic-Emacs-Comment `// -*- coding: utf-8-unix; Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-`')
            elif _match2:
                LINE_NUM += 1
                continue
        elif LINE_NUM == 2:  # MG0*: Magic-Vim-Comment
            _match = REGEX_VIM.search(LINE)
            _match2 = REGEX_VIM_VALID.search(LINE)
            if _match and not _match2:
                output_info(FILEPATH, LINE_NUM, LINE, r'MG03', r'Invalid format for Magic-Vim-Comment; use `// vim: set fileencoding=utf-8 filetype=c syntax=c.doxygen fileformat=unix tabstop=4 :`', _match)
            elif not _match:
                output_info(FILEPATH, LINE_NUM, r'', r'MG04', r'Missing Magic-Vim-Comment `// vim: set fileencoding=utf-8 filetype=c syntax=c.doxygen fileformat=unix tabstop=4 :`')
            elif _match2:
                LINE_NUM += 1
                continue
        elif LINE_NUM == 3:  # MG0*: Magic-Kate-Comment
            _match = REGEX_KATE.search(LINE)
            _match2 = REGEX_KATE_VALID.search(LINE)
            if _match and not _match2:
                output_info(FILEPATH, LINE_NUM, LINE, r'MG05', r'Invalid format for Magic-Kate-Comment; use `// kate: encoding utf-8; bom off; syntax c; indent-mode cstyle; eol unix; replace-tabs off; indent-width 4; tab-width 4; remove-trailing-space on; line-numbers on;`', _match)
            elif not _match:
                output_info(FILEPATH, LINE_NUM, r'', r'MG06', r'Missing Magic-Kate-Comment `// kate: encoding utf-8; bom off; syntax c; indent-mode cstyle; eol unix; replace-tabs off; indent-width 4; tab-width 4; remove-trailing-space on; line-numbers on;`')
            elif _match2:
                LINE_NUM += 1
                continue
        # Blank line
        if not LINE.strip():
            LINE_NUM += 1
            continue
        # Multi-line Comments
        NO_STR_LINE = strip_strings(LINE)  # Physical line without strings
        if (REGEX_COMMENT_MULTILINE_START.search(NO_STR_LINE) or REGEX_COMMENT_DOC.search(NO_STR_LINE)) and r'*/' not in NO_STR_LINE:  # Start of multiline-comment
            INSIDE_MULTILINE_COMMENT = True
            LINE_NUM += 1
            continue
        elif REGEX_COMMENT_MULTILINE_END.search(NO_STR_LINE) and r'/*' not in NO_STR_LINE:  # End of multiline-comment
            INSIDE_MULTILINE_COMMENT = False
            LINE_NUM += 1
            continue
        if INSIDE_MULTILINE_COMMENT:
            LINE_NUM += 1
            continue
        # Coding Lines
        LOGICAL_LINE = strip_comments_and_strings(LINE)  # Logical line without strings and comments
        if REGEX_COMMENT_LINE.search(LINE):  # Physical comment line
            t000(FILEPATH, LINE_NUM, LINE, LOGICAL_LINE)
            c000_line(FILEPATH, LINE_NUM, LINE, LOGICAL_LINE)
        elif r'#' in LINE and REGEX_MACROS.search(LINE):  # M*** (Macros)
            m000(FILEPATH, LINE_NUM, LINE, LOGICAL_LINE)
        elif not LINE.startswith(r'#'):  # Regular C-code (Non-macros)
            t000(FILEPATH, LINE_NUM, LINE, LOGICAL_LINE)
            c000(FILEPATH, LINE_NUM, LINE, LOGICAL_LINE)
            s000(FILEPATH, LINE_NUM, LINE, LOGICAL_LINE)
            v000(FILEPATH, LINE_NUM, LINE, LOGICAL_LINE)
            x000(FILEPATH, LINE_NUM, LINE, LOGICAL_LINE)
            z000(FILEPATH, LINE_NUM, LINE, LOGICAL_LINE)
        LINE_NUM += 1
        continue
