#!/bin/sh
# -*- coding: utf-8-unix; Mode: Shell; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=shell syn=sh.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax shell; indent-mode normal; eol unix; replace-tabs on; indent-width 4; tab-width 4; remove-trailing-space on;
#' @brief Wrapper for scanning CSS files with various syntax checkers
#' @file cssanalysis
#' @version 2019.12.26
#' @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
#' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/


if [ -z "${1:-}" ]; then
    printf 'ERROR: A parameter is required!\n' >&2
    exit 1
elif [ "$1" = '--help' ] || [ "$1" = 'help' ] || [ "$1" = '-h' ]; then
    printf 'Specify the pathname of each CSS file to scan.\n'
    exit 0
fi


# GLOBALS #


export LANG='en_US.UTF-8'
export LC_ALL='C'
export LC_CTYPE='C'


# SETUP COMMANDS #


CSSLINT_EXISTS=0
if [ -x "$(command -v csslint)" ]; then
    CSSLINT_EXISTS=1
else
    printf 'csslint: command not found!\n' >&2
fi

CODE_ANALYSIS_EXISTS=0
if [ -x "$(command -v code-analysis)" ]; then
    CODE_ANALYSIS_EXISTS=1
else
    printf 'code-analysis: command not found!\n' >&2
fi


# Use a faster alternative if possible
if [ -x "$(command -v mawk)" ]; then
    awk_cmd() { mawk "${1}"; }
elif [ -x "$(command -v nawk)" ]; then
    awk_cmd() { nawk "${1}"; }
else
    awk_cmd() { awk "${1}"; }
fi


# FUNCTIONS #


#' Run CSSLint
csslint_func() {
    if [ "$CSSLINT_EXISTS" -eq 1 ]; then
        printf '======  *CSSLINT*  ======\n'
        # shellcheck disable=SC1117
        csslint --format=text "${1}" | sed -E "s|^${1##*/}$||; s|^(.+): error at line ([0-9]+), col ([0-9]+)$|${1}:\2:\3:|; s|^(.+): warning at line ([0-9]+), col ([0-9]+)$|${1}:\2:\3:|" | awk_cmd '{ OFS=""; gsub(/^0$/, ""); if (NF > 0) { print; } }'
    fi
}


#' Run Code-Analysis
code_analysis_func() {
    if [ "$CODE_ANALYSIS_EXISTS" -eq 1 ]; then
        code-analysis "${1}"
    fi
}


# MAIN #


for file in "$@"; do
    { [ ! -r "$file" ] || [ -d "$file" ]; } && printf '%s: The specified file is non-readable or non-existent!\n' "$file" >&2 && continue

    CSSLINT_BUFFER="/tmp/$(uuid).cssanalysis.tmp"
    CODE_ANALYSIS_BUFFER="/tmp/$(uuid).cssanalysis.tmp"

    csslint_func "$file" > "${CSSLINT_BUFFER}" &
    code_analysis_func "$file" > "${CODE_ANALYSIS_BUFFER}" &

    wait

    printf "%s\\n%s\\n" "$(cat < "${CSSLINT_BUFFER}")" "$(cat < "${CODE_ANALYSIS_BUFFER}")"
    rm -f "${CSSLINT_BUFFER}" "${CODE_ANALYSIS_BUFFER}" || true


done
