#!/usr/bin/env python3
# -*- coding: utf-8; Mode: Python; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=python syntax=python.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax python; indent-mode python; eol unix; replace-tabs off; indent-width 4; tab-width 4; remove-trailing-space on;
# EASY-INSTALL-ENTRY-SCRIPT: "setuptools>=38.0","console_scripts","easy_install"
"""@brief Wrapper for easy-install

@file easy_install3
@version 2019.03.28
@author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
@copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/
"""


from pkg_resources import load_entry_point


__requires__: str = r'setuptools>=38.0'


if __name__ == '__main__':
    raise SystemExit(load_entry_point(__requires__, r'console_scripts', r'easy_install')())
