#!/usr/bin/env python3
# -*- coding: utf-8-unix; Mode: Python; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=python syntax=python.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax python; indent-mode python; eol unix; replace-tabs off; indent-width 4; tab-width 4; remove-trailing-space on; line-numbers on;
# EASY-INSTALL-ENTRY-SCRIPT: "flake8>=3.2.0","console_scripts","flake8"
"""@brief Wrapper for flake8

@file flake8
@version 2018.09.11
@author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
@copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/
"""


from re import sub
from sys import argv

from pkg_resources import load_entry_point


__requires__ = r'flake8>=3.2.0'


if __name__ == '__main__':
    argv[0] = sub(r'(-script\.pyw?|\.exe)?$', r'', argv[0])
    raise SystemExit(load_entry_point(__requires__, r'console_scripts', r'flake8')())
