#!/bin/sh
# -*- coding: utf-8-unix; Mode: Shell; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=shell syn=sh.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax shell; indent-mode normal; eol unix; replace-tabs on; indent-width 4; tab-width 4; remove-trailing-space on; line-numbers on;
#' @brief Wrapper for scanning JSON files with various syntax checkers
#' @file jsonanalysis
#' @version 2018.10.02
#' @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
#' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/


if [ "$1" = '--help' ] || [ "$1" = 'help' ] || [ "$1" = '-h' ]; then
    printf 'Specify the pathname of each JSON file to scan.\n'
    exit 0
elif [ -z "$1" ]; then
    printf 'ERROR: A parameter is required!\n' >&2
    exit 1
fi


export FirstLoopPass=0


# MAIN #


for file in "$@"; do
    ([ ! -r "$file" ] || [ -d "$file" ]) && printf '%s: The specified file is non-readable or non-existent!\n' "$file" >&2 && continue

    if [ -x "$(command -v jsonlint-php)" ]; then
        printf '======  *JSONLINT*  ======\n'
        jsonlint-php "$file" | awk '{ OFS=""; gsub(/^Valid JSON .+$/, ""); print $0; }' | awk NF
    elif [ "$FirstLoopPass" -eq 0 ]; then
        printf 'jsonlint-php: command not found!\n' >&2
    fi

    if [ -x "$(command -v json_verify)" ]; then
        printf '======  *JSON_VERIFY*  ======\n'
        json_verify -c < "$file" | awk '{ OFS=""; gsub(/^JSON is valid$/, ""); print $0; }' | awk NF
    elif [ "$FirstLoopPass" -eq 0 ]; then
        printf 'json_verify: command not found!\n' >&2
    fi

    if [ -x "$(command -v jsonlint-py3)" ]; then
        printf '======  *JSONLINT-PY3*  ======\n'
        jsonlint-py3 --strict "$file" | awk '{ OFS=""; gsub(/^.+: ok$/, ""); print $0; }' | awk NF
    elif [ "$FirstLoopPass" -eq 0 ]; then
        printf 'jsonlint-py3: command not found!\n' >&2
    fi

    if [ -x "$(command -v code-analysis)" ]; then
        code-analysis "$file"
    elif [ "$FirstLoopPass" -eq 0 ]; then
        printf 'code-analysis: command not found!\n' >&2
    fi

    FirstLoopPass=1

done
