#!/usr/bin/env python3
# -*- coding: utf-8; Mode: Python; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=python syntax=python.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax python; indent-mode python; eol unix; replace-tabs off; indent-width 4; tab-width 4; remove-trailing-space on;
# EASY-INSTALL-ENTRY-SCRIPT: "stdeb>=0.8.5","console_scripts","stdeb"
"""@brief Convert a distutils-built source tarball into a Debian source package (script wrapper)

@file py2dsc-deb
@version 2019.03.28
@author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
@copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/
"""


import stdeb.cli_runner


USAGE = r"""
Usage: py2dsc [options] distfile
   or: py2dsc --help
where distfile is a *.zip or *.tar.gz built with the sdist command
"""


if __name__ == '__main__':
    raise SystemExit(stdeb.cli_runner.runit(cmd=r'sdist_dsc', usage=USAGE))
