#!/usr/bin/env python3
# -*- coding: utf-8; Mode: Python; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=python syntax=python.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax python; indent-mode python; eol unix; replace-tabs off; indent-width 4; tab-width 4; remove-trailing-space on;
# EASY-INSTALL-ENTRY-SCRIPT: "pyflakes>=1.6.0","console_scripts","pyflakes"
"""@brief Wrapper for Pyflakes

@file pyflakes3
@version 2019.03.28
@author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
@copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/
"""


from re import sub
from sys import argv

from pyflakes.api import main


if __name__ == '__main__':
    argv[0] = sub(r'(-script\.pyw?|\.exe)?$', r'', argv[0])
    raise SystemExit(main())
