#!/bin/sh
# -*- coding: utf-8-unix; Mode: Shell; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=shell syn=sh.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax shell; indent-mode normal; eol unix; replace-tabs on; indent-width 4; tab-width 4; remove-trailing-space on;
#' @brief Graph the classes of a Python3 project
#' @file pygraphclasses3
#' @version 2019.07.05
#' @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
#' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/


if [ ! -x "$(command -v pyreverse)" ]; then
    printf 'pyreverse: command not found!\n' >&2
    exit 1
elif [ ! -x "$(command -v dot)" ]; then
    printf 'dot: command not found!\n' >&2
    exit 1
elif [ "${1:-}" = '--help' ] || [ "${1:-}" = '-h' ]; then
    printf 'pygraphclasses3 DIRECTORY PROJECT_NAME\n'
fi


if [ -z "${1:-}" ]; then
    printf 'The directory name of the project must be specified!\n' >&2
    exit 1
elif [ -z "${2:-}" ]; then
    printf 'The name of the project must be specified!\n' >&2
    exit 1
fi


save_path="${PWD}"

cd "${1}" || exit 1
pyreverse3 --all-ancestors --all-associated ./* && mv "./classes.dot" "./packages.dot" "${HOME}" && dot -Tsvg -o "${HOME}/${2}_Classes.svg" "${HOME}/classes.dot" && dot -Tsvg -o "${HOME}/${2}_Packages.svg" "${HOME}/packages.dot"
cd "${save_path}" || exit 1


if [ ! -f "${HOME}/${2}_Packages.svg" ]; then
    exit 1
fi

exit 0
