#!/usr/bin/env python3
# -*- coding: utf-8-unix; Mode: Python; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=python syntax=python.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax python; indent-mode python; eol unix; replace-tabs off; indent-width 4; tab-width 4; remove-trailing-space on; line-numbers on;
# EASY-INSTALL-ENTRY-SCRIPT: "pytest>=3.3.0","console_scripts","pytest"
"""@brief Pytest3 (Script Wrapper)

@file pytest3
@version 2018.10.13
@author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
@copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/
"""


from re import sub
from sys import argv

from pkg_resources import load_entry_point


__requires__: str = r'pytest>=3.3.0'


if __name__ == '__main__':
    argv[0] = sub(r'(-script\.pyw?|\.exe)?$', r'', argv[0])
    raise SystemExit(load_entry_point(__requires__, r'console_scripts', r'pytest')())
