#!/bin/sh
# -*- coding: utf-8-unix; Mode: Shell; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=shell syn=sh.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax shell; indent-mode normal; eol unix; replace-tabs on; indent-width 4; tab-width 4; remove-trailing-space on; line-numbers on;
#' @brief Recreate GRUB's entries and the Linux kernel's module-list
#' @file refreshgrub
#' @version 2018.09.11
#' @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
#' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/


if [ ! "$(id -u)" -eq 0 ]; then
    exec sudo -- "$0"
else
    if [ -x "$(command -v depmod)" ] && [ -x "$(command -v update-initramfs)" ] && [ -x "$(command -v update-grub2)" ]; then
        depmod -a -v && update-initramfs -u -v && update-grub2
        exit $?
    else
        printf 'ERROR: depmod, update-initramfs, and update-grub2 are required!\n' >&2
        exit 1
    fi
fi
