#!/bin/sh
# -*- coding: utf-8-unix; Mode: Shell; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=shell syn=sh.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax shell; indent-mode normal; eol unix; replace-tabs on; indent-width 4; tab-width 4; remove-trailing-space on;
#' @brief Set the access and modification times of the listed file to values from the given CSV file
#' @file setfiletimes
#' @version 2019.07.28
#' @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
#' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/


if [ "$1" = '--help' ] || [ "$1" = 'help' ] || [ "$1" = '-h' ]; then
    printf 'Specify the pathname of a directory in which to change the access-times of files.\n'
    exit 0
elif [ -z "${1:-}" ] || [ -z "${2:-}" ]; then
    printf 'ERROR: Two parameters are required!\n' >&2
    exit 1
elif [ ! -d "${1:-}" ]; then
    printf 'ERROR: The given path must be a directory!\n' >&2
    exit 1
elif [ ! -f "${2:-}" ]; then
    printf 'ERROR: The provided filepath is not a valid file!\n' >&2
    exit 1
fi


export IFS=','


while read -r filename accessed modified; do
    echo "${filename} : ${accessed} | ${modified}"
    touch -a -d "${accessed}" "${filename}"
    touch -m -d "${modified}" "${filename}"
done < "${2}"


exit 0
