#!/bin/sh
# -*- coding: utf-8-unix; Mode: Shell; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=shell syn=sh.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax shell; indent-mode normal; eol unix; replace-tabs on; indent-width 4; tab-width 4; remove-trailing-space on; line-numbers on;
#' @brief Delete thumbnails
#' @file thumbnail-cleaner
#' @version 2018.10.02
#' @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
#' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/


rm -f -r ~/.cache/thumbnails/ ~/.cache/thumbnail/ ~/.thumbnails/ ~/.thumbnail/ ~/.mandelbulb*/thumbnails/ ~/.miro/icon-cache/ ~/.purple/icons/ 2> /dev/null || true
exit 0
