#!/bin/sh
# -*- coding: utf-8-unix; Mode: Shell; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=shell syn=sh.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax shell; indent-mode normal; eol unix; replace-tabs on; indent-width 4; tab-width 4; remove-trailing-space on;
#' @brief Scan a whole directory structure recursively and list all reminder notes (e.g. "Todo" comments)
#' @file todo-scanner
#' @version 2019.03.28
#' @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
#' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/


# GLOBAL VALUES #


readonly COMMENT_PATTERNS="###!|##|#|#\'|\/\/\/|\/\/!|\/\/\'|\/\/|\/\*\*|\/\*!|\/\*|<!\-\-|;"
readonly REMINDER_PATTERN="DEBUG|DEPRECATED|DISABLED|FINISH|FIX|FIXME|REPAIR|TESTING|TODEBUG|TODO|TOMV|TORM|XXX"
readonly FILTER="[^A-Z0-9_=\\\"\'\.\?!@]*"


# VALIDATE PARAMETERS #


if [ -z "${1:-}" ]; then
    printf 'ERROR: A parameter is required!\n' >&2
    exit 1
elif [ "$1" = '--help' ] || [ "$1" = 'help' ] || [ "$1" = '-h' ]; then
    printf 'Specify the pathname of the directory to scan.\n'
    exit 0
elif [ -f "$1" ] || [ ! -d "$1" ]; then
    printf 'ERROR: A directory path is required!\n' >&2
    exit 1
fi


# MAIN #


grep -E -H -i -n -o -r "^.*${FILTER}(${COMMENT_PATTERNS})[ \t]*(${REMINDER_PATTERN})[ \t]*:[ \t]*.+$" "$1" | sed -E -e "/^[^:]+\.(cfg|conf|config|ini):[0-9]+:.+=.*[^A-Z0-9]+.+$/Id; s/^([^:]+):([0-9]+):.+[^A-Z0-9_]+[ \t]*(${REMINDER_PATTERN})[ \t]*:[ \t]*(.+)$/\1:\2:\3: \4/i;"
exit 0
