#!/usr/bin/env python3
# -*- coding: utf-8-unix; Mode: Python; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=python syntax=python.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax python; indent-mode python; eol unix; replace-tabs off; indent-width 4; tab-width 4; remove-trailing-space on; line-numbers on;
"""@brief Convert single-quotes to double-quotes and vice versa

@file togglequotes
@version 2018.09.11
@author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
@copyright LGPLv3

@section DESCRIPTION
This script can be integrated into Geany to toggle quotes.
Configure Geany: Edit→Format→Send Selection to→Set Custom Commands

@section LICENSE
GNU Lesser General Public License v3
Copyright (c) Devyn Collier Johnson, All rights reserved.

This software is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This software is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this software.
"""


from sys import argv, stderr, stdin, stdout


if __name__ == '__main__':
    if len(argv) == 1:  # Pipe
        DATA = stdin.read()
        if r'"' in DATA:
            stdout.write(DATA.replace(r'"', '\''))
        else:
            stdout.write(DATA.replace('\'', r'"'))
    elif argv[1].lower() in (r'help', r'--help', r'-h', r'--usage', r'?'):  # Help
        stdout.write('Usage 1: command | togglequotes\nUsage 2: togglequotes "string" \nConvert single-quotes to double-quotes and vice versa\n')
    elif argv[1]:  # String in argument
        DATA = argv[1]
        if not DATA.strip():
            stderr.write('No input found!\n')
        elif r'"' in DATA:
            stdout.write(DATA.replace(r'"', '\'') + '\n')
        else:
            stdout.write(DATA.replace('\'', r'"') + '\n')
    else:  # Help
        stdout.write('Usage 1: command | togglequotes\nUsage 2: togglequotes "string" \nConvert single-quotes to double-quotes and vice versa\n')
