#!/bin/sh
# -*- coding: utf-8-unix; Mode: Shell; indent-tabs-mode: nil; tab-width: 4 -*-
# vim: set fileencoding=utf-8 filetype=shell syn=sh.doxygen fileformat=unix tabstop=4 expandtab :
# kate: encoding utf-8; bom off; syntax shell; indent-mode normal; eol unix; replace-tabs on; indent-width 4; tab-width 4; remove-trailing-space on; line-numbers on;
#' @brief Wrapper for scanning XML files (i.e. HTML, MathML, SVG, & more) with various syntax checkers
#' @file xmlanalysis
#' @version 2018.10.02
#' @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
#' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/


if [ "$1" = '--help' ] || [ "$1" = 'help' ] || [ "$1" = '-h' ]; then
    printf 'Specify the pathname of each XML file to scan.\n'
    exit 0
elif [ -z "$1" ]; then
    printf 'ERROR: A parameter is required!\n' >&2
    exit 1
fi


export FirstLoopPass=0


# MAIN #


for file in "$@"; do
    ([ ! -r "$file" ] || [ -d "$file" ]) && printf '%s: The specified file is non-readable or non-existent!\n' "$file" >&2 && continue
    (head -1 "$file" | grep -v -F -e '<' > /dev/null) && (tail -2 "$file" | grep -v -F -e '>' > /dev/null) && printf '%s: The specified file is not an XML file!\n' "$file" >&2 && continue

    if [ -x "$(command -v weblint)" ] && (head -5 "$file" | grep -F -e '<!DOCTYPE html' > /dev/null); then
        printf '======  *WEBLINT*  ======\n'
        weblint --context=1 --fluff --helper --structure "$file" | awk '{ OFS=""; gsub(/^0$/, ""); print $0; }' | awk NF
    elif [ "$FirstLoopPass" -eq 0 ]; then
        printf 'weblint: command not found!\n' >&2
    fi

    if [ -x "$(command -v xmllint)" ]; then
        printf '======  *XMLLINT*  ======\n'
        if (head -5 "$file" | grep -F -e '<!DOCTYPE html' > /dev/null); then
            xmllint --valid --nowarning --noout --html "$file" | awk '{ OFS=""; gsub(/^0$/, ""); print $0; }' | awk NF
        else
            xmllint --valid --nowarning --noout "$file" | awk '{ OFS=""; gsub(/^0$/, ""); print $0; }' | awk NF
        fi
    elif [ "$FirstLoopPass" -eq 0 ]; then
        printf 'xmllint: command not found!\n' >&2
    fi

    if [ -x "$(command -v code-analysis)" ]; then
        code-analysis "$file"
    elif [ "$FirstLoopPass" -eq 0 ]; then
        printf 'code-analysis: command not found!\n' >&2
    fi

    FirstLoopPass=1

done
