PyBooster: cryptx.h File Reference
cryptx.h File Reference
Cryptography Functions (header)
#include "MACROS.h"
#include <time.h>
Data Structures
struct quaternion_crypt_byte
Macros
#define byteswap16(x) endianswap16((x))
#define byteswap32(x) endianswap32((x))
#define byteswap64(x) endianswap64((x))
#define byteswap8(x) endianswap8((x))
#define TREYFER_NUMROUNDS ((uint8_t)(32))
Functions
uint128_t adler128 (const uint8_t *__restrict__ data, register size_t len) __attribute__((const
uint16_t adler16 (const uint8_t *__restrict__ data, register size_t len) __attribute__((const
uint32_t adler32 (const uint8_t *__restrict__ data, register size_t len) __attribute__((const
uint64_t adler64 (const uint8_t *__restrict__ data, register size_t len) __attribute__((const
uint8_t adler8 (const uint8_t *__restrict__ data, register size_t len) __attribute__((const
uint64_t antiadler64 (const uint8_t *__restrict__ data, register size_t len) __attribute__((const
uint64_t antiadler64rev2 (const uint8_t *__restrict__ data, register size_t len) __attribute__((const
void array_rotl (uint8_t *__restrict__ array, const size_t len, const uint32_t num_shifts) __attribute__((nonnull))
void array_rotl64 (uint8_t *__restrict__ array, const uint64_t len, const uint64_t num_shifts) __attribute__((nonnull))
void array_rotr (uint8_t *__restrict__ array, const size_t len, const uint32_t num_shifts) __attribute__((nonnull))
void array_rotr64 (uint8_t *__restrict__ array, const uint64_t len, const uint64_t num_shifts) __attribute__((nonnull))
uint8_t bitparity (const uint32_t data) __attribute__((const
uint8_t bitparity128 (const uint128_t data)
uint8_t bitparity64 (const uint64_t data) __attribute__((const
void byte_rotl (uint8_t byte, const uint8_t num)
void byte_rotr (uint8_t byte, const uint8_t num)
void caesar_cipher (char *__restrict__ data, const ulint shift) __attribute__((nonnull))
void chararray_rotl (char *__restrict__ array, const size_t len, const uint32_t num_shifts) __attribute__((nonnull))
void chararray_rotl64 (char *__restrict__ array, const uint64_t len, const uint64_t num_shifts) __attribute__((nonnull))
void chararray_rotr (char *__restrict__ array, const size_t len, const uint32_t num_shifts) __attribute__((nonnull))
void chararray_rotr64 (char *__restrict__ array, const uint64_t len, const uint64_t num_shifts) __attribute__((nonnull))
uint32_t collier32 (const uint16_t *__restrict__ data, const size_t count) __attribute__((const
uint16_t crc16 (const uint8_t *__restrict__ data, size_t len)
uint16_t crc16mem (const uint16_t *ptr_crc, const uint8_t *data, const uint32_t len) __attribute__((const
uint16_t crc16memx (const uint8_t *data) __attribute__((const
uint16_t crc16x (const uint8_t *__restrict__ data) __attribute__((const
uint32_t crc32 (uint32_t crc, const uint8_t *__restrict__ data, const size_t len)
uint32_t crc32x (uint32_t crc, const uint8_t *__restrict__ data)
uint8_t crc8 (const uint8_t *__restrict__ data, size_t len)
uint8_t crc8portable (const uint8_t *__restrict__ data, const uint32_t len)
uint8_t crc8x (const uint8_t *__restrict__ data)
void decrypt_caesar_cipher (char *__restrict__ data, const ulint shift) __attribute__((nonnull))
void decrypt_tea_cipher (uint32_t *__restrict__ v, const uint32_t *__restrict__ k)
void decrypt_treyfer_cipher (uint8_t text[8], const uint8_t key[8])
void decrypt_xtea_cipher (const uint32_t num_rounds, uint32_t v[2], const uint32_t key[4])
uint16_t endianswap16 (uint16_t x) __attribute__((const))
uint32_t endianswap32 (uint32_t x) __attribute__((const))
uint64_t endianswap64 (uint64_t x) __attribute__((const))
uint8_t endianswap8 (uint8_t x) __attribute__((const))
uint16_t fletcher16 (const uint8_t *__restrict__ data, const size_t count) __attribute__((const
uint16_t fletcher16fast (const uint8_t *__restrict__ data, const size_t words) __attribute__((const
uint32_t fletcher32 (const uint16_t *__restrict__ data, const size_t count) __attribute__((const
uint32_t fletcher32fast (const uint16_t *__restrict__ data, const size_t words) __attribute__((const
uint64_t fletcher64 (const uint32_t *__restrict__ data, const size_t count) __attribute__((const
uint64_t fletcher64char (const uint8_t *__restrict__ data, const size_t count) __attribute__((const
uint8_t fletcher8 (const uint8_t *__restrict__ data, const size_t count) __attribute__((const
void nxor_cipher (char *__restrict__ data, const char *__restrict__ password) __attribute__((nonnull))
void quaternion_decryption32 (uint8_t *__restrict__ data, const uint32_t datasize, const uint8_t *__restrict__ key) __attribute__((flatten
void quaternion_decryption64 (uint8_t *__restrict__ data, const uint32_t datasize, const uint8_t *__restrict__ key) __attribute__((flatten
void quaternion_encryption32 (uint8_t *__restrict__ data, const uint32_t datasize, const uint8_t *__restrict__ key) __attribute__((flatten
void quaternion_encryption64 (uint8_t *__restrict__ data, const uint32_t datasize, const uint8_t *__restrict__ key) __attribute__((flatten
char * rand16384str (void)
char * randalphanumstr (const size_t length)
char * randalphastr (const size_t length)
int randomint (void)
ulint randomlong (void)
char * randstr (const size_t length)
char * randstrx (const uint64_t length)
void shuffle_int (signed int *__restrict__ array, const size_t num_items) __attribute__((nonnull))
void shuffle_uint32 (uint32_t *__restrict__ array, const uint32_t num_items) __attribute__((nonnull))
void tea_cipher (uint32_t *__restrict__ v, const uint32_t *__restrict__ k)
void treyfer_cipher (uint8_t text[8], const uint8_t key[8])
void xor_cipher (char *__restrict__ data, const char *__restrict__ password) __attribute__((nonnull))
void xtea_cipher (const uint32_t num_rounds, uint32_t v[2], const uint32_t key[4])
void xxtea_cipher (uint32_t *__restrict__ v, const int32_t num_items, const uint32_t key[4])
Variables
const u32 ANUBIS_RC []
const u32 ANUBIS_T0 [256]
const u32 ANUBIS_T1 [256]
const u32 ANUBIS_T2 [256]
const u32 ANUBIS_T3 [256]
const u32 ANUBIS_T4 [256]
const u32 ANUBIS_T5 [256]
const uint16_t crc16_table [256]
const uint32_t crc32_table [256]
uint8_t flatten
void nonnull
const uint8_t Sbox [256]
Detailed Description
Cryptography Functions (header)
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.25
DESCRIPTION
This library provides many encryption, decryption, cipher, hash, and checksum functions
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Definition in file cryptx.h.
Data Structure Documentation
struct quaternion_crypt_byte
Definition at line 51 of file cryptx.h.
Data Fields
uint8_t i
uint8_t j
uint8_t k
uint8_t R
Macro Definition Documentation
#define byteswap16 (x) endianswap16((x))
Definition at line 45 of file cryptx.h.
#define byteswap32 (x) endianswap32((x))
Definition at line 46 of file cryptx.h.
#define byteswap64 (x) endianswap64((x))
Definition at line 47 of file cryptx.h.
#define byteswap8 (x) endianswap8((x))
Definition at line 44 of file cryptx.h.
#define TREYFER_NUMROUNDS ((uint8_t)(32))
Definition at line 41 of file cryptx.h.
Referenced by decrypt_treyfer_cipher(), and treyfer_cipher().
Function Documentation
uint128_t adler128 (const uint8_t *__restrict__ data, register size_t len) const
uint16_t adler16 (const uint8_t *__restrict__ data, register size_t len) const
uint32_t adler32 (const uint8_t *__restrict__ data, register size_t len) const
uint64_t adler64 (const uint8_t *__restrict__ data, register size_t len) const
uint8_t adler8 (const uint8_t *__restrict__ data, register size_t len) const
uint64_t antiadler64 (const uint8_t *__restrict__ data, register size_t len) const
uint64_t antiadler64rev2 (const uint8_t *__restrict__ data, register size_t len) const
void array_rotl (uint8_t *__restrict__ array, const size_t len, const uint32_t num_shifts)
Rotate an array to the left in-place
Definition at line 886 of file cryptx.c.
void array_rotl64 (uint8_t *__restrict__ array, const uint64_t len, const uint64_t num_shifts)
Rotate an array to the left; supports larger arrays
Definition at line 900 of file cryptx.c.
void array_rotr (uint8_t *__restrict__ array, const size_t len, const uint32_t num_shifts)
Rotate an array to the right in-place
Definition at line 914 of file cryptx.c.
void array_rotr64 (uint8_t *__restrict__ array, const uint64_t len, const uint64_t num_shifts)
Rotate an array to the right; supports larger arrays
Definition at line 928 of file cryptx.c.
uint8_t bitparity (const uint32_t data) const
uint8_t bitparity128 (const uint128_t data)
Return the parity of the given data
Parameters
[in] data 128-bits of data
Returns
Parity
Definition at line 1318 of file cryptx.c.
uint8_t bitparity64 (const uint64_t data) const
void byte_rotl (uint8_t byte, const uint8_t num)
Rotate the byte to the left `num` times
Definition at line 873 of file cryptx.c.
Referenced by quaternion_decryption32(), and quaternion_decryption64().
void byte_rotr (uint8_t byte, const uint8_t num)
Rotate the byte to the right `num` times
Definition at line 879 of file cryptx.c.
Referenced by quaternion_encryption32(), and quaternion_encryption64().
void caesar_cipher (char *__restrict__ data, const ulint shift)
Encrypt a string using a weak and insecure Caesar Cipher
Definition at line 998 of file cryptx.c.
References strlenx(), and ulint.
void chararray_rotl (char *__restrict__ array, const size_t len, const uint32_t num_shifts)
Rotate a char array to the left in-place
Definition at line 942 of file cryptx.c.
void chararray_rotl64 (char *__restrict__ array, const uint64_t len, const uint64_t num_shifts)
Rotate a char array to the left; supports larger arrays
Definition at line 956 of file cryptx.c.
void chararray_rotr (char *__restrict__ array, const size_t len, const uint32_t num_shifts)
Rotate a char array to the right in-place
Definition at line 970 of file cryptx.c.
void chararray_rotr64 (char *__restrict__ array, const uint64_t len, const uint64_t num_shifts)
Rotate a char array to the right; supports larger arrays
Definition at line 984 of file cryptx.c.
uint32_t collier32 (const uint16_t *__restrict__ data, const size_t count) const
uint16_t crc16 (const uint8_t *__restrict__ data, size_t len)
Return the CRC16 value for the given byte array (`data`), given length
Parameters
[in] data Data
[in] len Length of data (in bytes)
Returns
CRC16 Checksum
Definition at line 1391 of file cryptx.c.
uint16_t crc16mem (const uint16_t * ptr_crc, const uint8_t * data, const uint32_t len) const
uint16_t crc16memx (const uint8_t * data) const
uint16_t crc16x (const uint8_t *__restrict__ data) const
uint32_t crc32 (uint32_t crc, const uint8_t *__restrict__ data, const size_t len)
Return the CRC32 value for the given byte array (`data`), given length
Parameters
[in] crc CRC Seed
[in] data Data
[in] len Length of data (in bytes)
Returns
CRC32 Checksum
Definition at line 1474 of file cryptx.c.
uint32_t crc32x (uint32_t crc, const uint8_t *__restrict__ data)
Return the CRC32 value for the given byte array (`data`)
Parameters
[in] crc CRC Seed
[in] data Data
Returns
CRC32 Checksum
Definition at line 1491 of file cryptx.c.
References strlenx_uint8().
uint8_t crc8 (const uint8_t *__restrict__ data, size_t len)
Return the CRC8 value for the given byte array (`data`), given length
Parameters
[in] data Data
[in] len Length of data (in bytes)
Returns
CRC8 Checksum
Definition at line 1334 of file cryptx.c.
uint8_t crc8portable (const uint8_t *__restrict__ data, const uint32_t len)
Return the CRC8 value for the given byte array (`data`), given length
Parameters
[in] data Data
[in] len Length of data (in bytes)
Returns
CRC8 Checksum
Definition at line 1370 of file cryptx.c.
uint8_t crc8x (const uint8_t *__restrict__ data)
Return the CRC8 value for the given byte array (`data`)
Parameters
[in] data Data
Returns
CRC8 Checksum
Definition at line 1351 of file cryptx.c.
References strlenx_uint8().
void decrypt_caesar_cipher (char *__restrict__ data, const ulint shift)
Decrypt a string using a Caesar Cipher
Definition at line 1007 of file cryptx.c.
References strlenx(), and ulint.
void decrypt_tea_cipher (uint32_t *__restrict__ v, const uint32_t *__restrict__ k)
Tiny Encryption Algorithm: Decrypt an array of two `uint32`s using an array of four `uint32`s
Definition at line 1055 of file cryptx.c.
void decrypt_treyfer_cipher (uint8_t text[8], const uint8_t key[8])
Treyfer Decryption
Definition at line 1155 of file cryptx.c.
References TREYFER_NUMROUNDS.
void decrypt_xtea_cipher (const uint32_t num_rounds, uint32_t v[2], const uint32_t key[4])
Extended Tiny Encryption Algorithm: Decrypt an array of two `uint32`s using an array of four `uint32`s
Definition at line 1084 of file cryptx.c.
uint16_t endianswap16 (uint16_t x) const
uint32_t endianswap32 (uint32_t x) const
uint64_t endianswap64 (uint64_t x) const
uint8_t endianswap8 (uint8_t x) const
uint16_t fletcher16 (const uint8_t *__restrict__ data, const size_t count) const
uint16_t fletcher16fast (const uint8_t *__restrict__ data, const size_t words) const
uint32_t fletcher32 (const uint16_t *__restrict__ data, const size_t count) const
uint32_t fletcher32fast (const uint16_t *__restrict__ data, const size_t words) const
uint64_t fletcher64 (const uint32_t *__restrict__ data, const size_t count) const
uint64_t fletcher64char (const uint8_t *__restrict__ data, const size_t count) const
uint8_t fletcher8 (const uint8_t *__restrict__ data, const size_t count) const
void nxor_cipher (char *__restrict__ data, const char *__restrict__ password)
Encrypt/Decrypt a string using an NXOR Cipher
Definition at line 1028 of file cryptx.c.
References strlenx().
void quaternion_decryption32 (uint8_t *__restrict__ data, const uint32_t datasize, const uint8_t *__restrict__ key)
void quaternion_decryption64 (uint8_t *__restrict__ data, const uint32_t datasize, const uint8_t *__restrict__ key)
void quaternion_encryption32 (uint8_t *__restrict__ data, const uint32_t datasize, const uint8_t *__restrict__ key)
void quaternion_encryption64 (uint8_t *__restrict__ data, const uint32_t datasize, const uint8_t *__restrict__ key)
char* rand16384str (void)
Return a random 16384-bit string; remember to `free()` random_string
Definition at line 766 of file cryptx.c.
References pybooster.timeutil::clock(), and ulint.
char* randalphanumstr (const size_t length)
Return a random alphanumeric string with the specified length; remember to `free()` random_string
Definition at line 720 of file cryptx.c.
References pybooster.timeutil::clock(), and ulint.
char* randalphastr (const size_t length)
Return a random alphabetic string with the specified length; remember to `free()` random_string
Definition at line 698 of file cryptx.c.
References pybooster.timeutil::clock(), and ulint.
int randomint (void)
Return a random integer
Definition at line 636 of file cryptx.c.
References pybooster.timeutil::clock().
ulint randomlong (void)
Return a random unsigned long int
Definition at line 649 of file cryptx.c.
References pybooster.timeutil::clock(), and ulint.
char* randstr (const size_t length)
Return a random string with the specified length; remember to `free()` random_string
Definition at line 676 of file cryptx.c.
References pybooster.timeutil::clock(), and ulint.
char* randstrx (const uint64_t length)
Return a random string with the specified length; supports larger strings; remember to `free()` random_string
Definition at line 742 of file cryptx.c.
References pybooster.timeutil::clock(), and ulint.
void shuffle_int (signed int *__restrict__ array, const size_t num_items)
Shuffle the int array; must have multiple array items and initialize srand()
Definition at line 818 of file cryptx.c.
void shuffle_uint32 (uint32_t *__restrict__ array, const uint32_t num_items)
Shuffle the uint32_t array; must have multiple array items and initialize srand()
Definition at line 833 of file cryptx.c.
void tea_cipher (uint32_t *__restrict__ v, const uint32_t *__restrict__ k)
Tiny Encryption Algorithm: Encrypt an array of two `uint32`s using an array of four `uint32`s
Definition at line 1040 of file cryptx.c.
void treyfer_cipher (uint8_t text[8], const uint8_t key[8])
Treyfer Encryption
Definition at line 1141 of file cryptx.c.
References TREYFER_NUMROUNDS, and TREYFER_ROTL.
void xor_cipher (char *__restrict__ data, const char *__restrict__ password)
Encrypt/Decrypt a string using an XOR Cipher
Definition at line 1016 of file cryptx.c.
References strlenx().
void xtea_cipher (const uint32_t num_rounds, uint32_t v[2], const uint32_t key[4])
Extended Tiny Encryption Algorithm: Encrypt an array of two `uint32`s using an array of four `uint32`s
Definition at line 1070 of file cryptx.c.
void xxtea_cipher (uint32_t *__restrict__ v, const int32_t num_items, const uint32_t key[4])
Corrected Block TEA: Encrypt/Decrypt an array of `num_items` `uint32_t`s using a four `uint32_t` key
Definition at line 1098 of file cryptx.c.
References DELTA, and MX.
Variable Documentation
const u32 ANUBIS_RC[]
Table of constants needed by some Anubis functions
Definition at line 623 of file cryptx.c.
const u32 ANUBIS_T0[256]
Table of constants needed by some Anubis functions
Definition at line 209 of file cryptx.c.
const u32 ANUBIS_T1[256]
Table of constants needed by some Anubis functions
Definition at line 278 of file cryptx.c.
const u32 ANUBIS_T2[256]
Table of constants needed by some Anubis functions
Definition at line 347 of file cryptx.c.
const u32 ANUBIS_T3[256]
Table of constants needed by some Anubis functions
Definition at line 416 of file cryptx.c.
const u32 ANUBIS_T4[256]
Table of constants needed by some Anubis functions
Definition at line 485 of file cryptx.c.
const u32 ANUBIS_T5[256]
Table of constants needed by some Anubis functions
Definition at line 554 of file cryptx.c.
const uint16_t crc16_table[256]
Table of constants needed by some CRC16 functions
Definition at line 66 of file cryptx.c.
const uint32_t crc32_table[256]
Table of constants needed by some CRC32 functions
Definition at line 103 of file cryptx.c.
uint32_t flatten
Definition at line 127 of file cryptx.h.
uint32_t nonnull
Definition at line 123 of file cryptx.h.
const uint8_t Sbox[256]
Table of constants needed by some cryptography functions
Definition at line 172 of file cryptx.c.