PyBooster: mathfunc.h File Reference
mathfunc.h File Reference
Mathematical and Trigonometric Functions (header)
#include "MACROS.h"
#include <math.h>
#include "MATH_MACROS.h"
#include "math_types.h"
Macros
#define cosiv(x) (vercos((x)))
#define covercos(x) (vercos((x)))
#define coversine(x) (vercos((x)))
#define cvc(x) (vercos((x)))
#define cvs(x) (vercos((x)))
#define hav(x) (haversin((x)))
#define qimag(x) ((x).i, (x).j, (x).k)
#define qimagf(x) ((x).i, (x).j, (x).k)
#define qimagl(x) ((x).i, (x).j, (x).k)
#define sinver(x) (versin((x)))
#define siv(x) (versin((x)))
#define vcs(x) (vercos((x)))
#define ver(x) (versin((x)))
#define vercosine(x) (vercos((x)))
#define vers(x) (versin((x)))
Functions
int abs_int (const int num) __attribute__((const
double absd (const double num) __attribute__((const
float absf (const float num) __attribute__((const
long double absl (const long double num) __attribute__((const
double acot (const double radians) __attribute__((const
float acotf (const float radians) __attribute__((const
double acoth (const double radians) __attribute__((const
float acothf (const float radians) __attribute__((const
long double acothl (const long double radians) __attribute__((const
long double acotl (const long double radians) __attribute__((const
double acsc (const double radians) __attribute__((const
float acscf (const float radians) __attribute__((const
double acsch (const double radians) __attribute__((const
float acschf (const float radians) __attribute__((const
long double acschl (const long double radians) __attribute__((const
long double acscl (const long double radians) __attribute__((const
double arc_angle (const double arc_length, const double radius) __attribute__((const))
double arccot (const double radians) __attribute__((const
float arccotf (const float radians) __attribute__((const
double arccoth (const double radians) __attribute__((const
float arccothf (const float radians) __attribute__((const
long double arccothl (const long double radians) __attribute__((const
long double arccotl (const long double radians) __attribute__((const
double arccsc (const double radians) __attribute__((const
float arccscf (const float radians) __attribute__((const
double arccsch (const double radians) __attribute__((const
float arccschf (const float radians) __attribute__((const
long double arccschl (const long double radians) __attribute__((const
long double arccscl (const long double radians) __attribute__((const
double arcexcot (const double radians) __attribute__((const
float arcexcotf (const float radians) __attribute__((const
double arcexcoth (const double radians) __attribute__((const
float arcexcothf (const float radians) __attribute__((const
long double arcexcothl (const long double radians) __attribute__((const
long double arcexcotl (const long double radians) __attribute__((const
double arcexcsc (const double radians) __attribute__((const
float arcexcscf (const float radians) __attribute__((const
double arcexcsch (const double radians) __attribute__((const
float arcexcschf (const float radians) __attribute__((const
long double arcexcschl (const long double radians) __attribute__((const
long double arcexcscl (const long double radians) __attribute__((const
double arcexsec (const double radians) __attribute__((const
float arcexsecf (const float radians) __attribute__((const
double arcexsech (const double radians) __attribute__((const
float arcexsechf (const float radians) __attribute__((const
long double arcexsechl (const long double radians) __attribute__((const
long double arcexsecl (const long double radians) __attribute__((const
double arcsec (const double radians) __attribute__((const
float arcsecf (const float radians) __attribute__((const
double arcsech (const double radians) __attribute__((const
float arcsechf (const float radians) __attribute__((const
long double arcsechl (const long double radians) __attribute__((const
long double arcsecl (const long double radians) __attribute__((const
double arcvercos (const double radians) __attribute__((const
float arcvercosf (const float radians) __attribute__((const
double arcvercosh (const double radians) __attribute__((const
float arcvercoshf (const float radians) __attribute__((const
long double arcvercoshl (const long double radians) __attribute__((const
long double arcvercosl (const long double radians) __attribute__((const
double arcversin (const double radians) __attribute__((const
float arcversinf (const float radians) __attribute__((const
double arcversinh (const double radians) __attribute__((const
float arcversinhf (const float radians) __attribute__((const
long double arcversinhl (const long double radians) __attribute__((const
long double arcversinl (const long double radians) __attribute__((const
double asec (const double radians) __attribute__((const
float asecf (const float radians) __attribute__((const
double asech (const double radians) __attribute__((const
float asechf (const float radians) __attribute__((const
long double asechl (const long double radians) __attribute__((const
long double asecl (const long double radians) __attribute__((const
double ATAN2 (const double y, const double x) __attribute__((const
uint128_t bit128_length (const uint128_t num) __attribute__((const
ullint bit_length (const ullint num) __attribute__((const
double complex cacot (const double complex radians) __attribute__((const
float complex cacotf (const float complex radians) __attribute__((const
double complex cacoth (const double complex radians) __attribute__((const
float complex cacothf (const float complex radians) __attribute__((const
long double complex cacothl (const long double complex radians) __attribute__((const
long double complex cacotl (const long double complex radians) __attribute__((const
double complex cacsc (const double complex radians) __attribute__((const
float complex cacscf (const float complex radians) __attribute__((const
double complex cacsch (const double complex radians) __attribute__((const
float complex cacschf (const float complex radians) __attribute__((const
long double complex cacschl (const long double complex radians) __attribute__((const
long double complex cacscl (const long double complex radians) __attribute__((const
double complex carccot (const double complex radians) __attribute__((const
float complex carccotf (const float complex radians) __attribute__((const
double complex carccoth (const double complex radians) __attribute__((const
float complex carccothf (const float complex radians) __attribute__((const
long double complex carccothl (const long double complex radians) __attribute__((const
long double complex carccotl (const long double complex radians) __attribute__((const
double complex carccsc (const double complex radians) __attribute__((const
float complex carccscf (const float complex radians) __attribute__((const
double complex carccsch (const double complex radians) __attribute__((const
float complex carccschf (const float complex radians) __attribute__((const
long double complex carccschl (const long double complex radians) __attribute__((const
long double complex carccscl (const long double complex radians) __attribute__((const
double complex carcexcot (const double complex radians) __attribute__((const
float complex carcexcotf (const float complex radians) __attribute__((const
double complex carcexcoth (const double complex radians) __attribute__((const
float complex carcexcothf (const float complex radians) __attribute__((const
long double complex carcexcothl (const long double complex radians) __attribute__((const
long double complex carcexcotl (const long double complex radians) __attribute__((const
double complex carcexcsc (const double complex radians) __attribute__((const
float complex carcexcscf (const float complex radians) __attribute__((const
double complex carcexcsch (const double complex radians) __attribute__((const
float complex carcexcschf (const float complex radians) __attribute__((const
long double complex carcexcschl (const long double complex radians) __attribute__((const
long double complex carcexcscl (const long double complex radians) __attribute__((const
double complex carcexsec (const double complex radians) __attribute__((const
float complex carcexsecf (const float complex radians) __attribute__((const
double complex carcexsech (const double complex radians) __attribute__((const
float complex carcexsechf (const float complex radians) __attribute__((const
long double complex carcexsechl (const long double complex radians) __attribute__((const
long double complex carcexsecl (const long double complex radians) __attribute__((const
double complex carcsec (const double complex radians) __attribute__((const
float complex carcsecf (const float complex radians) __attribute__((const
double complex carcsech (const double complex radians) __attribute__((const
float complex carcsechf (const float complex radians) __attribute__((const
long double complex carcsechl (const long double complex radians) __attribute__((const
long double complex carcsecl (const long double complex radians) __attribute__((const
double complex carcvercos (const double complex radians) __attribute__((const
float complex carcvercosf (const float complex radians) __attribute__((const
double complex carcvercosh (const double complex radians) __attribute__((const
float complex carcvercoshf (const float complex radians) __attribute__((const
long double complex carcvercoshl (const long double complex radians) __attribute__((const
long double complex carcvercosl (const long double complex radians) __attribute__((const
double complex carcversin (const double complex radians) __attribute__((const
float complex carcversinf (const float complex radians) __attribute__((const
double complex carcversinh (const double complex radians) __attribute__((const
float complex carcversinhf (const float complex radians) __attribute__((const
long double complex carcversinhl (const long double complex radians) __attribute__((const
long double complex carcversinl (const long double complex radians) __attribute__((const
double complex casec (const double complex radians) __attribute__((const
float complex casecf (const float complex radians) __attribute__((const
double complex casech (const double complex radians) __attribute__((const
float complex casechf (const float complex radians) __attribute__((const
long double complex casechl (const long double complex radians) __attribute__((const
long double complex casecl (const long double complex radians) __attribute__((const
double complex ccos_arcsin (const double complex radians) __attribute__((const
float complex ccos_arcsinf (const float complex radians) __attribute__((const
long double complex ccos_arcsinl (const long double complex radians) __attribute__((const
double complex ccos_arctan (const double complex radians) __attribute__((const
float complex ccos_arctanf (const float complex radians) __attribute__((const
long double complex ccos_arctanl (const long double complex radians) __attribute__((const
double complex ccot (const double complex radians) __attribute__((const
float complex ccotf (const float complex radians) __attribute__((const
double complex ccoth (const double complex radians) __attribute__((const
float complex ccothf (const float complex radians) __attribute__((const
long double complex ccothl (const long double complex radians) __attribute__((const
long double complex ccotl (const long double complex radians) __attribute__((const
double complex ccrd (const double complex radians) __attribute__((const
float complex ccrdf (const float complex radians) __attribute__((const
long double complex ccrdl (const long double complex radians) __attribute__((const
double complex ccsc (const double complex radians) __attribute__((const
float complex ccscf (const float complex radians) __attribute__((const
double complex ccsch (const double complex radians) __attribute__((const
float complex ccschf (const float complex radians) __attribute__((const
long double complex ccschl (const long double complex radians) __attribute__((const
long double complex ccscl (const long double complex radians) __attribute__((const
double complex cexcot (const double complex radians) __attribute__((const
float complex cexcotf (const float complex radians) __attribute__((const
double complex cexcoth (const double complex radians) __attribute__((const
float complex cexcothf (const float complex radians) __attribute__((const
long double complex cexcothl (const long double complex radians) __attribute__((const
long double complex cexcotl (const long double complex radians) __attribute__((const
double complex cexcsc (const double complex radians) __attribute__((const
float complex cexcscf (const float complex radians) __attribute__((const
double complex cexcsch (const double complex radians) __attribute__((const
float complex cexcschf (const float complex radians) __attribute__((const
long double complex cexcschl (const long double complex radians) __attribute__((const
long double complex cexcscl (const long double complex radians) __attribute__((const
double complex cexsec (const double complex radians) __attribute__((const
float complex cexsecf (const float complex radians) __attribute__((const
double complex cexsech (const double complex radians) __attribute__((const
float complex cexsechf (const float complex radians) __attribute__((const
long double complex cexsechl (const long double complex radians) __attribute__((const
long double complex cexsecl (const long double complex radians) __attribute__((const
double complex chacoversin (const double complex radians) __attribute__((const
float complex chacoversinf (const float complex radians) __attribute__((const
long double complex chacoversinl (const long double complex radians) __attribute__((const
double complex chaversin (const double complex radians) __attribute__((const
float complex chaversinf (const float complex radians) __attribute__((const
long double complex chaversinl (const long double complex radians) __attribute__((const
ullint clearlsb (ullint num) __attribute__((const
double complement_angle_deg (const double angle) __attribute__((const))
float complement_angle_degf (const float angle) __attribute__((const))
long double complement_angle_degl (const long double angle) __attribute__((const))
double complex conjugate (const double complex num)
float complex conjugatef (const float complex num)
long double complex conjugatel (const long double complex num)
double cos_arcsin (const double radians) __attribute__((const
float cos_arcsinf (const float radians) __attribute__((const
long double cos_arcsinl (const long double radians) __attribute__((const
double cos_arctan (const double radians) __attribute__((const
float cos_arctanf (const float radians) __attribute__((const
long double cos_arctanl (const long double radians) __attribute__((const
double cot (const double radians) __attribute__((const
float cotf (const float radians) __attribute__((const
double coth (const double radians) __attribute__((const
float cothf (const float radians) __attribute__((const
long double cothl (const long double radians) __attribute__((const
long double cotl (const long double radians) __attribute__((const
double crd (const double radians) __attribute__((const
float crdf (const float radians) __attribute__((const
long double crdl (const long double radians) __attribute__((const
double csc (const double radians) __attribute__((const
float cscf (const float radians) __attribute__((const
double csch (const double radians) __attribute__((const
float cschf (const float radians) __attribute__((const
long double cschl (const long double radians) __attribute__((const
long double cscl (const long double radians) __attribute__((const
double complex csec (const double complex radians) __attribute__((const
float complex csecf (const float complex radians) __attribute__((const
double complex csech (const double complex radians) __attribute__((const
float complex csechf (const float complex radians) __attribute__((const
long double complex csechl (const long double complex radians) __attribute__((const
long double complex csecl (const long double complex radians) __attribute__((const
double complex csin_arcsec (const double complex radians) __attribute__((const
float complex csin_arcsecf (const float complex radians) __attribute__((const
long double complex csin_arcsecl (const long double complex radians) __attribute__((const
double complex csin_arctan (const double complex radians) __attribute__((const
float complex csin_arctanf (const float complex radians) __attribute__((const
long double complex csin_arctanl (const long double complex radians) __attribute__((const
double complex cvercos (const double complex radians) __attribute__((const
float complex cvercosf (const float complex radians) __attribute__((const
double complex cvercosh (const double complex radians) __attribute__((const
float complex cvercoshf (const float complex radians) __attribute__((const
long double complex cvercoshl (const long double complex radians) __attribute__((const
long double complex cvercosl (const long double complex radians) __attribute__((const
double complex cversin (const double complex radians) __attribute__((const
float complex cversinf (const float complex radians) __attribute__((const
double complex cversinh (const double complex radians) __attribute__((const
float complex cversinhf (const float complex radians) __attribute__((const
long double complex cversinhl (const long double complex radians) __attribute__((const
long double complex cversinl (const long double complex radians) __attribute__((const
double div_and_mod (const double num1, const double num2) __attribute__((const
int div_and_mod_int (const int num1, const int num2) __attribute__((const
float div_and_modf (const float num1, const float num2) __attribute__((const
void dot_product32 (const int32_t *__restrict__ _array1, const int32_t *__restrict__ _array2, int32_t *output_array, const size_t _length) __attribute__((const
void dot_product64 (const int64_t *__restrict__ _array1, const int64_t *__restrict__ _array2, int64_t *output_array, const size_t _length) __attribute__((const
ullint doublefactorial (const unsigned int num) __attribute__((const
sllint doublefactoriallonglong (const sllint num) __attribute__((const
double excot (const double radians) __attribute__((const
float excotf (const float radians) __attribute__((const
double excoth (const double radians) __attribute__((const
float excothf (const float radians) __attribute__((const
long double excothl (const long double radians) __attribute__((const
long double excotl (const long double radians) __attribute__((const
double excsc (const double radians) __attribute__((const
float excscf (const float radians) __attribute__((const
double excsch (const double radians) __attribute__((const
float excschf (const float radians) __attribute__((const
long double excschl (const long double radians) __attribute__((const
long double excscl (const long double radians) __attribute__((const
double exp_minus1 (const double num) __attribute__((const
float exp_minus1f (const float num) __attribute__((const
long double exp_minus1l (const long double num) __attribute__((const
double exsec (const double radians) __attribute__((const
float exsecf (const float radians) __attribute__((const
double exsech (const double radians) __attribute__((const
float exsechf (const float radians) __attribute__((const
long double exsechl (const long double radians) __attribute__((const
long double exsecl (const long double radians) __attribute__((const
unsigned long long int factorial (const unsigned int num) __attribute__((const
sllint factoriallonglong (const sllint num) __attribute__((const
unsigned int fib (const unsigned int num) __attribute__((const
double hacoversin (const double radians) __attribute__((const
float hacoversinf (const float radians) __attribute__((const
long double hacoversinl (const long double radians) __attribute__((const
double haversin (const double radians) __attribute__((const
float haversinf (const float radians) __attribute__((const
long double haversinl (const long double radians) __attribute__((const
unsigned int heptagonal_num (const unsigned int num) __attribute__((const
sllint heptagonal_numlonglong (const sllint num) __attribute__((const
ullint heptagonal_numull (const ullint num) __attribute__((const
double heptagonal_root (const long num) __attribute__((const
uint128_t heptagonal_u128 (const uint128_t num) __attribute__((const
unsigned int hexagonal_num (const unsigned int num) __attribute__((const
sllint hexagonal_numlonglong (const sllint num) __attribute__((const
ullint hexagonal_numull (const ullint num) __attribute__((const
double hexagonal_root (const long num) __attribute__((const
uint128_t hexagonal_u128 (const uint128_t num) __attribute__((const
double ipow (double num, const int exp) __attribute__((const
int is_double_negative (double num) __attribute__((const
int is_double_positive (double num) __attribute__((const
int is_float_negative (float num) __attribute__((const
int is_float_positive (float num) __attribute__((const
int iscomposite (const int num) __attribute__((const
int isdoublesquare (const double num) __attribute__((const
int isdoubletriangular (const double num) __attribute__((const
int isfloatsquare (const float num) __attribute__((const
int isheptagonal (const long num) __attribute__((const
int ishexagonal (const long num) __attribute__((const
int islongcomposite (const long num) __attribute__((const
int islongdoublesquare (const long double num) __attribute__((const
int islonglongcomposite (const long long num) __attribute__((const
int islonglongheptagonal (const long long num) __attribute__((const
int islonglonghexagonal (const long long num) __attribute__((const
int islonglongmersennenumber (const sllint num) __attribute__((const
int islonglongmersenneprime (const long long num) __attribute__((const
int islonglongpoweroftwo (const long long num) __attribute__((const
int islonglongprime (const long long num) __attribute__((const
int islonglongsquare (const long long num) __attribute__((const
int islonglongtriangular (const long long num) __attribute__((const
int islongprime (const long num) __attribute__((const
int islongsquare (const long num) __attribute__((const
int ismersennenumber (const unsigned int num) __attribute__((const
int ismersenneprime (const unsigned int num) __attribute__((const
int ispoweroftwo (const unsigned int num) __attribute__((const
int isprime (const int num) __attribute__((const
uint16_t isqrt16 (const uint16_t num) __attribute__((const
uint32_t isqrt32 (const uint32_t num) __attribute__((const
uint64_t isqrt64 (const uint64_t num) __attribute__((const
uint8_t isqrt8 (const uint8_t num) __attribute__((const
int issquare (const int num) __attribute__((const
int istriangular (const long num) __attribute__((const
int isulcomposite (const ulint num) __attribute__((const
int isullcomposite (const ullint num) __attribute__((const
int isullpoweroftwo (const ullint num) __attribute__((const
int isullprime (const ullint num) __attribute__((const
int isulprime (const ulint num) __attribute__((const
int isunsignedcomposite (const unsigned int num) __attribute__((const
int isunsignedprime (const unsigned int num) __attribute__((const
double lanczos_sum (const double x) __attribute__((const
double ln (const double num) __attribute__((const
double lnp1 (const double num) __attribute__((const
double LOG (const double num) __attribute__((const
double LOG10 (const double num) __attribute__((const
double LOG2 (const double num) __attribute__((const
double log_plus1 (const double num) __attribute__((const
float log_plus1f (const float num) __attribute__((const
long double log_plus1l (const long double num) __attribute__((const
unsigned long int longfib (const unsigned long int num) __attribute__((const
sllint longlongfib (const sllint num) __attribute__((const
double longmean (const slint count,...) __attribute__((const
int max (const int count,...) __attribute__((const
double maxd (const int count,...) __attribute__((const
float maxf (const int count,...) __attribute__((const
double mean (const int count,...) __attribute__((const
float meanf (const int count,...) __attribute__((const
long double meanl (const long long int count,...) __attribute__((const
unsigned int mersenne_num (const unsigned int num) __attribute__((const
sllint mersenne_numlonglong (const sllint num) __attribute__((const
ullint mersenne_numull (const ullint num) __attribute__((const
uint128_t mersenne_u128 (const uint128_t num) __attribute__((const
int min (const int count,...) __attribute__((const
double mind (const int count,...) __attribute__((const
float minf (const int count,...) __attribute__((const
signed int mod_pow (const signed int base, const signed int exponent, const signed int modulus) __attribute__((const
sllint mod_pow_longlong (const sllint base, const sllint exponent, const sllint modulus) __attribute__((const
double norm (const double complex x)
float normf (const float complex x)
long double norml (const long double complex x)
unsigned int pentatope_num (const unsigned int num) __attribute__((const
sllint pentatope_numlonglong (const sllint num) __attribute__((const
ullint pentatope_numull (const ullint num) __attribute__((const
uint128_t pentatope_u128 (const uint128_t num) __attribute__((const
double poly (const double x, const size_t n, const double *__restrict__ c) __attribute__((const
unsigned long long int pow2 (const unsigned int num) __attribute__((const
signed long long int pow2_longlong (const signed long long int num) __attribute__((const
double pow_ten (const signed int num) __attribute__((const
unsigned long long int pow_ten_int (const unsigned int num) __attribute__((const
unsigned long long int pow_ten_int_fast (const unsigned int num) __attribute__((const
double pow_ten_neg (const signed int num) __attribute__((const
float pow_ten_negf (const signed int num) __attribute__((const
long double pow_ten_negl (const slint num) __attribute__((const
double pow_ten_pos (const unsigned int num) __attribute__((const
float pow_ten_posf (const unsigned int num) __attribute__((const
long double pow_ten_posl (const unsigned long int num) __attribute__((const
long double pow_tenl (const signed int num) __attribute__((const
unsigned int pronic (const unsigned int num) __attribute__((const
uint128_t pronic_u128 (const uint128_t num) __attribute__((const
sllint proniclonglong (const sllint num) __attribute__((const
ullint pronicull (const ullint num) __attribute__((const
quaternion qadd (const quaternion num1, const quaternion num2)
quaternion_float qaddf (const quaternion_float num1, const quaternion_float num2)
quaternion_long_double qaddl (const quaternion_long_double num1, const quaternion_long_double num2)
quaternion qconjugate (const quaternion num)
quaternion_float qconjugatef (const quaternion_float num)
quaternion_long_double qconjugatel (const quaternion_long_double num)
quaternion qdiv (const quaternion num1, const quaternion num2)
quaternion_float qdivf (const quaternion_float num1, const quaternion_float num2)
quaternion_long_double qdivl (const quaternion_long_double num1, const quaternion_long_double num2)
double qgeti (const quaternion num)
float qgetif (const quaternion_float num)
long double qgetil (const quaternion_long_double num)
double qgetj (const quaternion num)
float qgetjf (const quaternion_float num)
long double qgetjl (const quaternion_long_double num)
double qgetk (const quaternion num)
float qgetkf (const quaternion_float num)
long double qgetkl (const quaternion_long_double num)
quaternion qinv (const quaternion qnum)
void qinv_inplace (quaternion qnum)
void qinv_inplacef (quaternion_float qnum)
void qinv_inplacel (quaternion_long_double qnum)
quaternion_float qinvf (const quaternion_float qnum)
quaternion_long_double qinvl (const quaternion_long_double qnum)
double qlen (const quaternion num) __attribute__((const
float qlenf (const quaternion_float num) __attribute__((const
long double qlenl (const quaternion_long_double num) __attribute__((const
quaternion qmid (const quaternion num1, const quaternion num2) __attribute__((const
quaternion_float qmidf (const quaternion_float num1, const quaternion_float num2) __attribute__((const
quaternion_long_double qmidl (const quaternion_long_double num1, const quaternion_long_double num2) __attribute__((const
quaternion qmul (const quaternion num1, const quaternion num2)
quaternion_float qmulf (const quaternion_float num1, const quaternion_float num2)
quaternion_long_double qmull (const quaternion_long_double num1, const quaternion_long_double num2)
quaternion qneg (const quaternion qnum)
void qneg_inplace (quaternion qnum)
void qneg_inplacef (quaternion_float qnum)
void qneg_inplacel (quaternion_long_double qnum)
quaternion_float qnegf (const quaternion_float qnum)
quaternion_long_double qnegl (const quaternion_long_double qnum)
double qnorm (const quaternion num)
float qnormf (const quaternion_float num)
long double qnorml (const quaternion_long_double num)
double qreal (const quaternion num)
float qrealf (const quaternion_float num)
long double qreall (const quaternion_long_double num)
quaternion qscalar (const quaternion num)
quaternion_float qscalarf (const quaternion_float num)
quaternion_long_double qscalarl (const quaternion_long_double num)
quaternion qsqrt (const quaternion num) __attribute__((const
quaternion_float qsqrtf (const quaternion_float num) __attribute__((const
quaternion_long_double qsqrtl (const quaternion_long_double num) __attribute__((const
quaternion qsub (const quaternion num1, const quaternion num2)
quaternion_float qsubf (const quaternion_float num1, const quaternion_float num2)
quaternion_long_double qsubl (const quaternion_long_double num1, const quaternion_long_double num2)
ullint quadfactorial (const unsigned int num) __attribute__((const
sllint quadfactoriallonglong (const sllint num) __attribute__((const
quaternion qvector (const quaternion num)
quaternion_float qvectorf (const quaternion_float num)
quaternion_long_double qvectorl (const quaternion_long_double num)
quaternion qversor (const quaternion num)
quaternion_float qversorf (const quaternion_float num)
quaternion_long_double qversorl (const quaternion_long_double num)
double retint (const double x) __attribute__((const
double sawtooth (const double x) __attribute__((const
double sawtooth2 (const double x, const double period, const double amplitude) __attribute__((const
double sec (const double radians) __attribute__((const
float secf (const float radians) __attribute__((const
double sech (const double radians) __attribute__((const
float sechf (const float radians) __attribute__((const
long double sechl (const long double radians) __attribute__((const
long double secl (const long double radians) __attribute__((const
double sgn (const double num) __attribute__((const
signed int sgn_int (const signed int num) __attribute__((const
float sgnf (const float num) __attribute__((const
long double sgnl (const long double num) __attribute__((const
double sigmoid (const double x) __attribute__((const
double signed_pow (const signed int base, const signed int exponent) __attribute__((const
long double signed_powl (const slint base, const slint exponent) __attribute__((const
double sin_arcsec (const double radians) __attribute__((const
float sin_arcsecf (const float radians) __attribute__((const
long double sin_arcsecl (const long double radians) __attribute__((const
double sin_arctan (const double radians) __attribute__((const
float sin_arctanf (const float radians) __attribute__((const
long double sin_arctanl (const long double radians) __attribute__((const
double sin_wave_equation (const double amplitude, const double angle) __attribute__((const
double sinpi (const double num) __attribute__((const
uint8_t sqrt16 (const uint16_t num) __attribute__((const
uint16_t sqrt32 (const uint32_t num) __attribute__((const
uint32_t sqrt64 (const uint64_t num) __attribute__((const
ullint sqrtull (const ullint num) __attribute__((const
double squareroot (const double num) __attribute__((const
float squarerootf (const float num) __attribute__((const
long double squarerootl (const long double num) __attribute__((const
double squarewave (const double x) __attribute__((const
ullint superfactorial (const unsigned int num) __attribute__((const
sllint superfactoriallonglong (const sllint num) __attribute__((const
double supplement_angle_deg (const double angle) __attribute__((const))
float supplement_angle_degf (const float angle) __attribute__((const))
long double supplement_angle_degl (const long double angle) __attribute__((const))
unsigned int tetrahedral_num (const unsigned int num) __attribute__((const
sllint tetrahedral_numlonglong (const sllint num) __attribute__((const
ullint tetrahedral_numull (const ullint num) __attribute__((const
uint128_t tetrahedral_u128 (const uint128_t num) __attribute__((const
int trianglewave (const int x) __attribute__((const
unsigned int triangular_num (const unsigned int num) __attribute__((const
sllint triangular_numlonglong (const sllint num) __attribute__((const
ullint triangular_numull (const ullint num) __attribute__((const
double triangular_root (const long num) __attribute__((const
uint128_t triangular_u128 (const uint128_t num) __attribute__((const
int unfactorial (const int num) __attribute__((const
uint64_t unfactorial64 (const uint64_t num) __attribute__((const
ullint unsigned_pow (const unsigned int base, const unsigned int exponent) __attribute__((const
double vercos (const double radians) __attribute__((const
float vercosf (const float radians) __attribute__((const
double vercosh (const double radians) __attribute__((const
float vercoshf (const float radians) __attribute__((const
long double vercoshl (const long double radians) __attribute__((const
long double vercosl (const long double radians) __attribute__((const
double versin (const double radians) __attribute__((const
float versinf (const float radians) __attribute__((const
double versinh (const double radians) __attribute__((const
float versinhf (const float radians) __attribute__((const
long double versinhl (const long double radians) __attribute__((const
long double versinl (const long double radians) __attribute__((const
Variables
double flatten
void nonnull
Detailed Description
Mathematical and Trigonometric Functions (header)
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.25
DESCRIPTION
This library provides additional functions and offers faster alternatives to some standard functions. Some provided functions include squareroot, fractorial, fib, haversin, isprime, ishexagonal, etc.
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Definition in file mathfunc.h.
Macro Definition Documentation
#define cosiv (x) (vercos((x)))
Definition at line 52 of file mathfunc.h.
#define covercos (x) (vercos((x)))
Definition at line 49 of file mathfunc.h.
#define coversine (x) (vercos((x)))
Definition at line 51 of file mathfunc.h.
#define cvc (x) (vercos((x)))
Definition at line 50 of file mathfunc.h.
#define cvs (x) (vercos((x)))
Definition at line 53 of file mathfunc.h.
#define hav (x) (haversin((x)))
Definition at line 58 of file mathfunc.h.
#define qimag (x) ((x).i, (x).j, (x).k)
Definition at line 1049 of file mathfunc.h.
#define qimagf (x) ((x).i, (x).j, (x).k)
Definition at line 1076 of file mathfunc.h.
#define qimagl (x) ((x).i, (x).j, (x).k)
Definition at line 1103 of file mathfunc.h.
#define sinver (x) (versin((x)))
Definition at line 55 of file mathfunc.h.
#define siv (x) (versin((x)))
Definition at line 56 of file mathfunc.h.
#define vcs (x) (vercos((x)))
Definition at line 47 of file mathfunc.h.
#define ver (x) (versin((x)))
Definition at line 54 of file mathfunc.h.
#define vercosine (x) (vercos((x)))
Definition at line 48 of file mathfunc.h.
#define vers (x) (versin((x)))
Definition at line 57 of file mathfunc.h.
Function Documentation
int abs_int (const int num) const
double absd (const double num) const
float absf (const float num) const
long double absl (const long double num) const
double acot (const double radians) const
float acotf (const float radians) const
double acoth (const double radians) const
float acothf (const float radians) const
long double acothl (const long double radians) const
long double acotl (const long double radians) const
double acsc (const double radians) const
float acscf (const float radians) const
double acsch (const double radians) const
float acschf (const float radians) const
long double acschl (const long double radians) const
long double acscl (const long double radians) const
double arc_angle (const double arc_length, const double radius) const
double arccot (const double radians) const
float arccotf (const float radians) const
double arccoth (const double radians) const
float arccothf (const float radians) const
long double arccothl (const long double radians) const
long double arccotl (const long double radians) const
double arccsc (const double radians) const
float arccscf (const float radians) const
double arccsch (const double radians) const
float arccschf (const float radians) const
long double arccschl (const long double radians) const
long double arccscl (const long double radians) const
double arcexcot (const double radians) const
float arcexcotf (const float radians) const
double arcexcoth (const double radians) const
float arcexcothf (const float radians) const
long double arcexcothl (const long double radians) const
long double arcexcotl (const long double radians) const
double arcexcsc (const double radians) const
float arcexcscf (const float radians) const
double arcexcsch (const double radians) const
float arcexcschf (const float radians) const
long double arcexcschl (const long double radians) const
long double arcexcscl (const long double radians) const
double arcexsec (const double radians) const
float arcexsecf (const float radians) const
double arcexsech (const double radians) const
float arcexsechf (const float radians) const
long double arcexsechl (const long double radians) const
long double arcexsecl (const long double radians) const
double arcsec (const double radians) const
float arcsecf (const float radians) const
double arcsech (const double radians) const
float arcsechf (const float radians) const
long double arcsechl (const long double radians) const
long double arcsecl (const long double radians) const
double arcvercos (const double radians) const
float arcvercosf (const float radians) const
double arcvercosh (const double radians) const
float arcvercoshf (const float radians) const
long double arcvercoshl (const long double radians) const
long double arcvercosl (const long double radians) const
double arcversin (const double radians) const
float arcversinf (const float radians) const
double arcversinh (const double radians) const
float arcversinhf (const float radians) const
long double arcversinhl (const long double radians) const
long double arcversinl (const long double radians) const
double asec (const double radians) const
float asecf (const float radians) const
double asech (const double radians) const
float asechf (const float radians) const
long double asechl (const long double radians) const
long double asecl (const long double radians) const
double ATAN2 (const double y, const double x) const
uint128_t bit128_length (const uint128_t num) const
ullint bit_length (const ullint num) const
double complex cacot (const double complex radians) const
float complex cacotf (const float complex radians) const
double complex cacoth (const double complex radians) const
float complex cacothf (const float complex radians) const
long double complex cacothl (const long double complex radians) const
long double complex cacotl (const long double complex radians) const
double complex cacsc (const double complex radians) const
float complex cacscf (const float complex radians) const
double complex cacsch (const double complex radians) const
float complex cacschf (const float complex radians) const
long double complex cacschl (const long double complex radians) const
long double complex cacscl (const long double complex radians) const
double complex carccot (const double complex radians) const
float complex carccotf (const float complex radians) const
double complex carccoth (const double complex radians) const
float complex carccothf (const float complex radians) const
long double complex carccothl (const long double complex radians) const
long double complex carccotl (const long double complex radians) const
double complex carccsc (const double complex radians) const
float complex carccscf (const float complex radians) const
double complex carccsch (const double complex radians) const
float complex carccschf (const float complex radians) const
long double complex carccschl (const long double complex radians) const
long double complex carccscl (const long double complex radians) const
double complex carcexcot (const double complex radians) const
float complex carcexcotf (const float complex radians) const
double complex carcexcoth (const double complex radians) const
float complex carcexcothf (const float complex radians) const
long double complex carcexcothl (const long double complex radians) const
long double complex carcexcotl (const long double complex radians) const
double complex carcexcsc (const double complex radians) const
float complex carcexcscf (const float complex radians) const
double complex carcexcsch (const double complex radians) const
float complex carcexcschf (const float complex radians) const
long double complex carcexcschl (const long double complex radians) const
long double complex carcexcscl (const long double complex radians) const
double complex carcexsec (const double complex radians) const
float complex carcexsecf (const float complex radians) const
double complex carcexsech (const double complex radians) const
float complex carcexsechf (const float complex radians) const
long double complex carcexsechl (const long double complex radians) const
long double complex carcexsecl (const long double complex radians) const
double complex carcsec (const double complex radians) const
float complex carcsecf (const float complex radians) const
double complex carcsech (const double complex radians) const
float complex carcsechf (const float complex radians) const
long double complex carcsechl (const long double complex radians) const
long double complex carcsecl (const long double complex radians) const
double complex carcvercos (const double complex radians) const
float complex carcvercosf (const float complex radians) const
double complex carcvercosh (const double complex radians) const
float complex carcvercoshf (const float complex radians) const
long double complex carcvercoshl (const long double complex radians) const
long double complex carcvercosl (const long double complex radians) const
double complex carcversin (const double complex radians) const
float complex carcversinf (const float complex radians) const
double complex carcversinh (const double complex radians) const
float complex carcversinhf (const float complex radians) const
long double complex carcversinhl (const long double complex radians) const
long double complex carcversinl (const long double complex radians) const
double complex casec (const double complex radians) const
float complex casecf (const float complex radians) const
double complex casech (const double complex radians) const
float complex casechf (const float complex radians) const
long double complex casechl (const long double complex radians) const
long double complex casecl (const long double complex radians) const
double complex ccos_arcsin (const double complex radians) const
float complex ccos_arcsinf (const float complex radians) const
long double complex ccos_arcsinl (const long double complex radians) const
double complex ccos_arctan (const double complex radians) const
float complex ccos_arctanf (const float complex radians) const
long double complex ccos_arctanl (const long double complex radians) const
double complex ccot (const double complex radians) const
float complex ccotf (const float complex radians) const
double complex ccoth (const double complex radians) const
float complex ccothf (const float complex radians) const
long double complex ccothl (const long double complex radians) const
long double complex ccotl (const long double complex radians) const
double complex ccrd (const double complex radians) const
float complex ccrdf (const float complex radians) const
long double complex ccrdl (const long double complex radians) const
double complex ccsc (const double complex radians) const
float complex ccscf (const float complex radians) const
double complex ccsch (const double complex radians) const
float complex ccschf (const float complex radians) const
long double complex ccschl (const long double complex radians) const
long double complex ccscl (const long double complex radians) const
double complex cexcot (const double complex radians) const
float complex cexcotf (const float complex radians) const
double complex cexcoth (const double complex radians) const
float complex cexcothf (const float complex radians) const
long double complex cexcothl (const long double complex radians) const
long double complex cexcotl (const long double complex radians) const
double complex cexcsc (const double complex radians) const
float complex cexcscf (const float complex radians) const
double complex cexcsch (const double complex radians) const
float complex cexcschf (const float complex radians) const
long double complex cexcschl (const long double complex radians) const
long double complex cexcscl (const long double complex radians) const
double complex cexsec (const double complex radians) const
float complex cexsecf (const float complex radians) const
double complex cexsech (const double complex radians) const
float complex cexsechf (const float complex radians) const
long double complex cexsechl (const long double complex radians) const
long double complex cexsecl (const long double complex radians) const
double complex chacoversin (const double complex radians) const
float complex chacoversinf (const float complex radians) const
long double complex chacoversinl (const long double complex radians) const
double complex chaversin (const double complex radians) const
float complex chaversinf (const float complex radians) const
long double complex chaversinl (const long double complex radians) const
ullint clearlsb (ullint num) const
double complement_angle_deg (const double angle) const
float complement_angle_degf (const float angle) const
long double complement_angle_degl (const long double angle) const
double complex conjugate (const double complex num)
Return the conjugate of a complex number
Definition at line 3828 of file mathfunc.c.
References I_DOUBLE.
float complex conjugatef (const float complex num)
Return the conjugate of a complex number
Definition at line 3840 of file mathfunc.c.
References I_FLOAT.
long double complex conjugatel (const long double complex num)
Return the conjugate of a complex number
Definition at line 3834 of file mathfunc.c.
References I_LONG_DOUBLE.
double cos_arcsin (const double radians) const
float cos_arcsinf (const float radians) const
long double cos_arcsinl (const long double radians) const
double cos_arctan (const double radians) const
float cos_arctanf (const float radians) const
long double cos_arctanl (const long double radians) const
double cot (const double radians) const
float cotf (const float radians) const
double coth (const double radians) const
float cothf (const float radians) const
long double cothl (const long double radians) const
long double cotl (const long double radians) const
double crd (const double radians) const
float crdf (const float radians) const
long double crdl (const long double radians) const
double csc (const double radians) const
float cscf (const float radians) const
double csch (const double radians) const
float cschf (const float radians) const
long double cschl (const long double radians) const
long double cscl (const long double radians) const
double complex csec (const double complex radians) const
float complex csecf (const float complex radians) const
double complex csech (const double complex radians) const
float complex csechf (const float complex radians) const
long double complex csechl (const long double complex radians) const
long double complex csecl (const long double complex radians) const
double complex csin_arcsec (const double complex radians) const
float complex csin_arcsecf (const float complex radians) const
long double complex csin_arcsecl (const long double complex radians) const
double complex csin_arctan (const double complex radians) const
float complex csin_arctanf (const float complex radians) const
long double complex csin_arctanl (const long double complex radians) const
double complex cvercos (const double complex radians) const
float complex cvercosf (const float complex radians) const
double complex cvercosh (const double complex radians) const
float complex cvercoshf (const float complex radians) const
long double complex cvercoshl (const long double complex radians) const
long double complex cvercosl (const long double complex radians) const
double complex cversin (const double complex radians) const
float complex cversinf (const float complex radians) const
double complex cversinh (const double complex radians) const
float complex cversinhf (const float complex radians) const
long double complex cversinhl (const long double complex radians) const
long double complex cversinl (const long double complex radians) const
double div_and_mod (const double num1, const double num2) const
int div_and_mod_int (const int num1, const int num2) const
float div_and_modf (const float num1, const float num2) const
void dot_product32 (const int32_t *__restrict__ _array1, const int32_t *__restrict__ _array2, int32_t * output_array, const size_t _length) const
void dot_product64 (const int64_t *__restrict__ _array1, const int64_t *__restrict__ _array2, int64_t * output_array, const size_t _length) const
ullint doublefactorial (const unsigned int num) const
sllint doublefactoriallonglong (const sllint num) const
double excot (const double radians) const
float excotf (const float radians) const
double excoth (const double radians) const
float excothf (const float radians) const
long double excothl (const long double radians) const
long double excotl (const long double radians) const
double excsc (const double radians) const
float excscf (const float radians) const
double excsch (const double radians) const
float excschf (const float radians) const
long double excschl (const long double radians) const
long double excscl (const long double radians) const
double exp_minus1 (const double num) const
float exp_minus1f (const float num) const
long double exp_minus1l (const long double num) const
double exsec (const double radians) const
float exsecf (const float radians) const
double exsech (const double radians) const
float exsechf (const float radians) const
long double exsechl (const long double radians) const
long double exsecl (const long double radians) const
unsigned long long int factorial (const unsigned int num) const
sllint factoriallonglong (const sllint num) const
unsigned int fib (const unsigned int num) const
double hacoversin (const double radians) const
float hacoversinf (const float radians) const
long double hacoversinl (const long double radians) const
double haversin (const double radians) const
float haversinf (const float radians) const
long double haversinl (const long double radians) const
unsigned int heptagonal_num (const unsigned int num) const
sllint heptagonal_numlonglong (const sllint num) const
ullint heptagonal_numull (const ullint num) const
double heptagonal_root (const long num) const
uint128_t heptagonal_u128 (const uint128_t num) const
unsigned int hexagonal_num (const unsigned int num) const
sllint hexagonal_numlonglong (const sllint num) const
ullint hexagonal_numull (const ullint num) const
double hexagonal_root (const long num) const
uint128_t hexagonal_u128 (const uint128_t num) const
double ipow (double num, const int exp) const
int is_double_negative (double num) const
int is_double_positive (double num) const
int is_float_negative (float num) const
int is_float_positive (float num) const
int iscomposite (const int num) const
int isdoublesquare (const double num) const
int isdoubletriangular (const double num) const
int isfloatsquare (const float num) const
int isheptagonal (const long num) const
int ishexagonal (const long num) const
int islongcomposite (const long num) const
int islongdoublesquare (const long double num) const
int islonglongcomposite (const long long num) const
int islonglongheptagonal (const long long num) const
int islonglonghexagonal (const long long num) const
int islonglongmersennenumber (const sllint num) const
int islonglongmersenneprime (const long long num) const
int islonglongpoweroftwo (const long long num) const
int islonglongprime (const long long num) const
int islonglongsquare (const long long num) const
int islonglongtriangular (const long long num) const
int islongprime (const long num) const
int islongsquare (const long num) const
int ismersennenumber (const unsigned int num) const
int ismersenneprime (const unsigned int num) const
int ispoweroftwo (const unsigned int num) const
int isprime (const int num) const
uint16_t isqrt16 (const uint16_t num) const
uint32_t isqrt32 (const uint32_t num) const
uint64_t isqrt64 (const uint64_t num) const
uint8_t isqrt8 (const uint8_t num) const
int issquare (const int num) const
int istriangular (const long num) const
int isulcomposite (const ulint num) const
int isullcomposite (const ullint num) const
int isullpoweroftwo (const ullint num) const
int isullprime (const ullint num) const
int isulprime (const ulint num) const
int isunsignedcomposite (const unsigned int num) const
int isunsignedprime (const unsigned int num) const
double lanczos_sum (const double x) const
double ln (const double num) const
double lnp1 (const double num) const
double LOG (const double num) const
double LOG10 (const double num) const
double LOG2 (const double num) const
double log_plus1 (const double num) const
float log_plus1f (const float num) const
long double log_plus1l (const long double num) const
unsigned long int longfib (const unsigned long int num) const
sllint longlongfib (const sllint num) const
double longmean (const slint count, ...) const
int max (const int count, ...) const
double maxd (const int count, ...) const
float maxf (const int count, ...) const
double mean (const int count, ...) const
float meanf (const int count, ...) const
long double meanl (const long long int count, ...) const
unsigned int mersenne_num (const unsigned int num) const
sllint mersenne_numlonglong (const sllint num) const
ullint mersenne_numull (const ullint num) const
uint128_t mersenne_u128 (const uint128_t num) const
int min (const int count, ...) const
double mind (const int count, ...) const
float minf (const int count, ...) const
signed int mod_pow (const signed int base, const signed int exponent, const signed int modulus) const
sllint mod_pow_longlong (const sllint base, const sllint exponent, const sllint modulus) const
double norm (const double complex x)
Return the norm value of the complex number
Definition at line 3847 of file mathfunc.c.
References squareroot().
float normf (const float complex x)
Return the norm value of the complex number
Definition at line 3867 of file mathfunc.c.
References squarerootf().
long double norml (const long double complex x)
Return the norm value of the complex number
Definition at line 3857 of file mathfunc.c.
References squarerootl().
unsigned int pentatope_num (const unsigned int num) const
sllint pentatope_numlonglong (const sllint num) const
ullint pentatope_numull (const ullint num) const
uint128_t pentatope_u128 (const uint128_t num) const
double poly (const double x, const size_t n, const double *__restrict__ c) const
unsigned long long int pow2 (const unsigned int num) const
signed long long int pow2_longlong (const signed long long int num) const
double pow_ten (const signed int num) const
unsigned long long int pow_ten_int (const unsigned int num) const
unsigned long long int pow_ten_int_fast (const unsigned int num) const
double pow_ten_neg (const signed int num) const
float pow_ten_negf (const signed int num) const
long double pow_ten_negl (const slint num) const
double pow_ten_pos (const unsigned int num) const
float pow_ten_posf (const unsigned int num) const
long double pow_ten_posl (const unsigned long int num) const
long double pow_tenl (const signed int num) const
unsigned int pronic (const unsigned int num) const
uint128_t pronic_u128 (const uint128_t num) const
sllint proniclonglong (const sllint num) const
ullint pronicull (const ullint num) const
quaternion qadd (const quaternion num1, const quaternion num2)
Add two quaternion numbers
Definition at line 3915 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
Referenced by qmid().
quaternion_float qaddf (const quaternion_float num1, const quaternion_float num2)
Add two quaternion numbers
Definition at line 4069 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
Referenced by qmidf().
quaternion_long_double qaddl (const quaternion_long_double num1, const quaternion_long_double num2)
Add two quaternion numbers
Definition at line 4223 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
Referenced by qmidl().
quaternion qconjugate (const quaternion num)
Return the conjugate of the quaternion number
Definition at line 3903 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
quaternion_float qconjugatef (const quaternion_float num)
Return the conjugate of the quaternion number
Definition at line 4057 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
quaternion_long_double qconjugatel (const quaternion_long_double num)
Return the conjugate of the quaternion number
Definition at line 4211 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
quaternion qdiv (const quaternion num1, const quaternion num2)
Divide two quaternion numbers
Definition at line 3937 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, quaternion::R, and squareroot().
Referenced by qversor().
quaternion_float qdivf (const quaternion_float num1, const quaternion_float num2)
Divide two quaternion numbers
Definition at line 4091 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, quaternion_float::R, and squarerootf().
Referenced by qversorf().
quaternion_long_double qdivl (const quaternion_long_double num1, const quaternion_long_double num2)
Divide two quaternion numbers
Definition at line 4245 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, quaternion_long_double::R, and squarerootl().
Referenced by qversorl().
double qgeti (const quaternion num)
Return the imaginary i num of the quaternion number
Definition at line 3885 of file mathfunc.c.
References quaternion::i.
float qgetif (const quaternion_float num)
Return the imaginary i num of the quaternion number
Definition at line 4039 of file mathfunc.c.
References quaternion_float::i.
long double qgetil (const quaternion_long_double num)
Return the imaginary i num of the quaternion number
Definition at line 4193 of file mathfunc.c.
References quaternion_long_double::i.
double qgetj (const quaternion num)
Return the imaginary j num of the quaternion number
Definition at line 3891 of file mathfunc.c.
References quaternion::j.
float qgetjf (const quaternion_float num)
Return the imaginary j num of the quaternion number
Definition at line 4045 of file mathfunc.c.
References quaternion_float::j.
long double qgetjl (const quaternion_long_double num)
Return the imaginary j num of the quaternion number
Definition at line 4199 of file mathfunc.c.
References quaternion_long_double::j.
double qgetk (const quaternion num)
Return the imaginary k num of the quaternion number
Definition at line 3897 of file mathfunc.c.
References quaternion::k.
float qgetkf (const quaternion_float num)
Return the imaginary k num of the quaternion number
Definition at line 4051 of file mathfunc.c.
References quaternion_float::k.
long double qgetkl (const quaternion_long_double num)
Return the imaginary k num of the quaternion number
Definition at line 4205 of file mathfunc.c.
References quaternion_long_double::k.
quaternion qinv (const quaternion qnum)
Inverse quaternion
Definition at line 3949 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
void qinv_inplace (quaternion qnum)
Inverse quaternion (in-place)
Definition at line 3956 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
void qinv_inplacef (quaternion_float qnum)
Inverse quaternion (in-place)
Definition at line 4110 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
void qinv_inplacel (quaternion_long_double qnum)
Inverse quaternion (in-place)
Definition at line 4264 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
quaternion_float qinvf (const quaternion_float qnum)
Inverse quaternion
Definition at line 4103 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
quaternion_long_double qinvl (const quaternion_long_double qnum)
Inverse quaternion
Definition at line 4257 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
double qlen (const quaternion num) const
float qlenf (const quaternion_float num) const
long double qlenl (const quaternion_long_double num) const
quaternion qmid (const quaternion num1, const quaternion num2) const
quaternion_float qmidf (const quaternion_float num1, const quaternion_float num2) const
quaternion_long_double qmidl (const quaternion_long_double num1, const quaternion_long_double num2) const
quaternion qmul (const quaternion num1, const quaternion num2)
Multiply two quaternion numbers
Definition at line 3927 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
quaternion_float qmulf (const quaternion_float num1, const quaternion_float num2)
Multiply two quaternion numbers
Definition at line 4081 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
quaternion_long_double qmull (const quaternion_long_double num1, const quaternion_long_double num2)
Multiply two quaternion numbers
Definition at line 4235 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
quaternion qneg (const quaternion qnum)
Return the negative quaternion
Definition at line 3966 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
void qneg_inplace (quaternion qnum)
Negate quaternion (in-place)
Definition at line 3972 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
void qneg_inplacef (quaternion_float qnum)
Negate quaternion (in-place)
Definition at line 4126 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
void qneg_inplacel (quaternion_long_double qnum)
Negate quaternion (in-place)
Definition at line 4280 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
quaternion_float qnegf (const quaternion_float qnum)
Return the negative quaternion
Definition at line 4120 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
quaternion_long_double qnegl (const quaternion_long_double qnum)
Return the negative quaternion
Definition at line 4274 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
double qnorm (const quaternion num)
Return the norm value of the quaternion number
Definition at line 3909 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, quaternion::R, and squareroot().
float qnormf (const quaternion_float num)
Return the norm value of the quaternion number
Definition at line 4063 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, quaternion_float::R, and squarerootf().
long double qnorml (const quaternion_long_double num)
Return the norm value of the quaternion number
Definition at line 4217 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, quaternion_long_double::R, and squarerootl().
double qreal (const quaternion num)
Return the real number from the quaternion number
Definition at line 3879 of file mathfunc.c.
References quaternion::R.
float qrealf (const quaternion_float num)
Return the real number from the quaternion number
Definition at line 4033 of file mathfunc.c.
References quaternion_float::R.
long double qreall (const quaternion_long_double num)
Return the real number from the quaternion number
Definition at line 4187 of file mathfunc.c.
References quaternion_long_double::R.
quaternion qscalar (const quaternion num)
Return the scalar portion of the quaternion number
Definition at line 4012 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
quaternion_float qscalarf (const quaternion_float num)
Return the scalar portion of the quaternion number
Definition at line 4166 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
quaternion_long_double qscalarl (const quaternion_long_double num)
Return the scalar portion of the quaternion number
Definition at line 4320 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
quaternion qsqrt (const quaternion num) const
quaternion_float qsqrtf (const quaternion_float num) const
quaternion_long_double qsqrtl (const quaternion_long_double num) const
quaternion qsub (const quaternion num1, const quaternion num2)
Subtract two quaternion numbers
Definition at line 3921 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
quaternion_float qsubf (const quaternion_float num1, const quaternion_float num2)
Subtract two quaternion numbers
Definition at line 4075 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
quaternion_long_double qsubl (const quaternion_long_double num1, const quaternion_long_double num2)
Subtract two quaternion numbers
Definition at line 4229 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
ullint quadfactorial (const unsigned int num) const
sllint quadfactoriallonglong (const sllint num) const
quaternion qvector (const quaternion num)
Return the vector portion of the quaternion number
Definition at line 4019 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, and quaternion::R.
quaternion_float qvectorf (const quaternion_float num)
Return the vector portion of the quaternion number
Definition at line 4173 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, and quaternion_float::R.
quaternion_long_double qvectorl (const quaternion_long_double num)
Return the vector portion of the quaternion number
Definition at line 4327 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, and quaternion_long_double::R.
quaternion qversor (const quaternion num)
Return the versor the quaternion number
Definition at line 4026 of file mathfunc.c.
References quaternion::i, quaternion::j, quaternion::k, qdiv(), and quaternion::R.
quaternion_float qversorf (const quaternion_float num)
Return the versor the quaternion number
Definition at line 4180 of file mathfunc.c.
References quaternion_float::i, quaternion_float::j, quaternion_float::k, qdivf(), and quaternion_float::R.
quaternion_long_double qversorl (const quaternion_long_double num)
Return the versor the quaternion number
Definition at line 4334 of file mathfunc.c.
References quaternion_long_double::i, quaternion_long_double::j, quaternion_long_double::k, qdivl(), and quaternion_long_double::R.
double retint (const double x) const
double sawtooth (const double x) const
double sawtooth2 (const double x, const double period, const double amplitude) const
double sec (const double radians) const
float secf (const float radians) const
double sech (const double radians) const
float sechf (const float radians) const
long double sechl (const long double radians) const
long double secl (const long double radians) const
double sgn (const double num) const
signed int sgn_int (const signed int num) const
float sgnf (const float num) const
long double sgnl (const long double num) const
double sigmoid (const double x) const
double signed_pow (const signed int base, const signed int exponent) const
long double signed_powl (const slint base, const slint exponent) const
double sin_arcsec (const double radians) const
float sin_arcsecf (const float radians) const
long double sin_arcsecl (const long double radians) const
double sin_arctan (const double radians) const
float sin_arctanf (const float radians) const
long double sin_arctanl (const long double radians) const
double sin_wave_equation (const double amplitude, const double angle) const
double sinpi (const double num) const
uint8_t sqrt16 (const uint16_t num) const
uint16_t sqrt32 (const uint32_t num) const
uint32_t sqrt64 (const uint64_t num) const
ullint sqrtull (const ullint num) const
double squareroot (const double num) const
float squarerootf (const float num) const
long double squarerootl (const long double num) const
double squarewave (const double x) const
ullint superfactorial (const unsigned int num) const
sllint superfactoriallonglong (const sllint num) const
double supplement_angle_deg (const double angle) const
float supplement_angle_degf (const float angle) const
long double supplement_angle_degl (const long double angle) const
unsigned int tetrahedral_num (const unsigned int num) const
sllint tetrahedral_numlonglong (const sllint num) const
ullint tetrahedral_numull (const ullint num) const
uint128_t tetrahedral_u128 (const uint128_t num) const
int trianglewave (const int x) const
unsigned int triangular_num (const unsigned int num) const
sllint triangular_numlonglong (const sllint num) const
ullint triangular_numull (const ullint num) const
double triangular_root (const long num) const
uint128_t triangular_u128 (const uint128_t num) const
int unfactorial (const int num) const
uint64_t unfactorial64 (const uint64_t num) const
ullint unsigned_pow (const unsigned int base, const unsigned int exponent) const
double vercos (const double radians) const
float vercosf (const float radians) const
double vercosh (const double radians) const
float vercoshf (const float radians) const
long double vercoshl (const long double radians) const
long double vercosl (const long double radians) const
double versin (const double radians) const
float versinf (const float radians) const
double versinh (const double radians) const
float versinhf (const float radians) const
long double versinhl (const long double radians) const
long double versinl (const long double radians) const
Variable Documentation
void flatten
Definition at line 79 of file mathfunc.h.
void nonnull
Definition at line 1151 of file mathfunc.h.