PyBooster: pybooster.neuralnet Namespace Reference
pybooster.neuralnet Namespace Reference
Data Structures
class NeuroCode
Neurocode class.
Functions
def _indent
Indent the given code.
def flatten
Flatten list of lists.
Variables
list __all__
Detailed Description
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.25
DESCRIPTION
 from pybooster.neuralnet import NeuroCode
 data = [  # The input and output of an XOR gate
     ([0, 0], [0]),
     ([0, 1], [1]),
     ([1, 0], [1]),
     ([1, 1], [0])
 ]  # Provide sample input and expected output
 net = NeuroCode(
     data,
     layers = [4, 3],  # Number of nodes in each hidden layers (between input and output)
     iterations = 40000,   # Maximum training iterations
     rate = 0.1  # Learning rate
 )
 net.train()  # Returns (correctness, iterations)
 output = net.run([1, 0])  # Execute neuralnet
 net.writedump('xor_code.py')  # Save the generated code
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
The PyBooster Library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Function Documentation
def pybooster.neuralnet._indent (txt) private
Indent the given code.
Definition at line 83 of file neuralnet.py.
Referenced by NeuroCode.to_c_function(), NeuroCode.to_function(), and NeuroCode.to_java_method().
def pybooster.neuralnet.flatten (_lst)
Flatten list of lists.
Definition at line 71 of file neuralnet.py.
Variable Documentation
list __all__
Initial value:
 = [
     'flatten',
     'NeuroCode',
 ]
Definition at line 64 of file neuralnet.py.