PyBooster: pymathfunc.c File Reference
pymathfunc.c File Reference
Mathematical and Trigonometric Functions from mathfunc.c.
#include "PY_MACROS.h"
#include "mathfunc.h"
Macros
#define MODINIT PyMODINIT_FUNC PyInit_mathfunc(void)
#define MODNAME "mathfunc"
Functions
MODINIT __attribute__ ((flatten, hot))
if (return m==(PyObject *) NULL)
static PyObject * mathfunc_acot (FUNCARGS)
static PyObject * mathfunc_acoth (FUNCARGS)
static PyObject * mathfunc_acsc (FUNCARGS)
static PyObject * mathfunc_acsch (FUNCARGS)
static PyObject * mathfunc_arccot (FUNCARGS)
static PyObject * mathfunc_arccoth (FUNCARGS)
static PyObject * mathfunc_arccsc (FUNCARGS)
static PyObject * mathfunc_arccsch (FUNCARGS)
static PyObject * mathfunc_arcexcot (FUNCARGS)
static PyObject * mathfunc_arcexcoth (FUNCARGS)
static PyObject * mathfunc_arcexcsc (FUNCARGS)
static PyObject * mathfunc_arcexcsch (FUNCARGS)
static PyObject * mathfunc_arcexsec (FUNCARGS)
static PyObject * mathfunc_arcexsech (FUNCARGS)
static PyObject * mathfunc_arcsec (FUNCARGS)
static PyObject * mathfunc_arcsech (FUNCARGS)
static PyObject * mathfunc_arcvercos (FUNCARGS)
static PyObject * mathfunc_arcvercosh (FUNCARGS)
static PyObject * mathfunc_arcversin (FUNCARGS)
static PyObject * mathfunc_arcversinh (FUNCARGS)
static PyObject * mathfunc_asec (FUNCARGS)
static PyObject * mathfunc_asech (FUNCARGS)
static PyObject * mathfunc_bit_length (FUNCARGS)
static PyObject * mathfunc_cos_arcsin (FUNCARGS)
static PyObject * mathfunc_cos_arctan (FUNCARGS)
static PyObject * mathfunc_cot (FUNCARGS)
static PyObject * mathfunc_coth (FUNCARGS)
static PyObject * mathfunc_crd (FUNCARGS)
static PyObject * mathfunc_csc (FUNCARGS)
static PyObject * mathfunc_csch (FUNCARGS)
static PyObject * mathfunc_doublefactorial (FUNCARGS)
static PyObject * mathfunc_excot (FUNCARGS)
static PyObject * mathfunc_excoth (FUNCARGS)
static PyObject * mathfunc_excsc (FUNCARGS)
static PyObject * mathfunc_excsch (FUNCARGS)
static PyObject * mathfunc_exsec (FUNCARGS)
static PyObject * mathfunc_exsech (FUNCARGS)
static PyObject * mathfunc_factorial (FUNCARGS)
static PyObject * mathfunc_fib (FUNCARGS)
static PyObject * mathfunc_float_diff (FUNCARGS)
static PyObject * mathfunc_fma (FUNCARGS)
static PyObject * mathfunc_fpclassify (FUNCARGS)
static PyObject * mathfunc_hacoversin (FUNCARGS)
static PyObject * mathfunc_haversin (FUNCARGS)
static PyObject * mathfunc_heptagonal_num (FUNCARGS)
static PyObject * mathfunc_hexagonal_num (FUNCARGS)
static PyObject * mathfunc_iscomposite (FUNCARGS)
static PyObject * mathfunc_isfloatsquare (FUNCARGS)
static PyObject * mathfunc_isheptagonal (FUNCARGS)
static PyObject * mathfunc_ishexagonal (FUNCARGS)
static PyObject * mathfunc_ismersennenumber (FUNCARGS)
static PyObject * mathfunc_ismersenneprime (FUNCARGS)
static PyObject * mathfunc_ispoweroftwo (FUNCARGS)
static PyObject * mathfunc_isprime (FUNCARGS)
static PyObject * mathfunc_issquare (FUNCARGS)
static PyObject * mathfunc_istriangular (FUNCARGS)
static PyObject * mathfunc_mersenne_num (FUNCARGS)
static PyObject * mathfunc_pentatope_num (FUNCARGS)
static PyObject * mathfunc_pow2 (FUNCARGS)
static PyObject * mathfunc_pow_ten (FUNCARGS)
static PyObject * mathfunc_pow_ten_int (FUNCARGS)
static PyObject * mathfunc_pow_ten_int_fast (FUNCARGS)
static PyObject * mathfunc_pow_ten_neg (FUNCARGS)
static PyObject * mathfunc_pow_ten_pos (FUNCARGS)
static PyObject * mathfunc_pronic (FUNCARGS)
static PyObject * mathfunc_quadfactorial (FUNCARGS)
static PyObject * mathfunc_sec (FUNCARGS)
static PyObject * mathfunc_sech (FUNCARGS)
static PyObject * mathfunc_sin_arcsec (FUNCARGS)
static PyObject * mathfunc_sin_arctan (FUNCARGS)
static PyObject * mathfunc_sinpi (FUNCARGS)
static PyObject * mathfunc_squareroot (FUNCARGS)
static PyObject * mathfunc_superfactorial (FUNCARGS)
static PyObject * mathfunc_tetrahedral_num (FUNCARGS)
static PyObject * mathfunc_triangular_num (FUNCARGS)
static PyObject * mathfunc_vercos (FUNCARGS)
static PyObject * mathfunc_vercosh (FUNCARGS)
static PyObject * mathfunc_versin (FUNCARGS)
static PyObject * mathfunc_versinh (FUNCARGS)
PyModule_AddStringConstant (m,"__author__", __author__)
PyModule_AddStringConstant (m,"__version__", __version__)
Variables
m = PyModule_Create(&module)
MODINIT
static struct PyModuleDef module
Detailed Description
Mathematical and Trigonometric Functions from mathfunc.c.
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.21
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Definition in file pymathfunc.c.
Macro Definition Documentation
#define MODINIT PyMODINIT_FUNC PyInit_mathfunc(void)
Definition at line 34 of file pymathfunc.c.
#define MODNAME "mathfunc"
Definition at line 33 of file pymathfunc.c.
Function Documentation
MODINIT __attribute__ ((flatten, hot))
if (return m = = (PyObject *)NULL)
Definition at line 527 of file pymathfunc.c.
static PyObject* mathfunc_acot (FUNCARGS) static
Definition at line 739 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_acoth (FUNCARGS) static
Definition at line 753 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_acsc (FUNCARGS) static
Definition at line 781 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_acsch (FUNCARGS) static
Definition at line 795 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_arccot (FUNCARGS) static
Definition at line 746 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_arccoth (FUNCARGS) static
Definition at line 760 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_arccsc (FUNCARGS) static
Definition at line 788 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_arccsch (FUNCARGS) static
Definition at line 802 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_arcexcot (FUNCARGS) static
Definition at line 938 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_arcexcoth (FUNCARGS) static
Definition at line 945 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_arcexcsc (FUNCARGS) static
Definition at line 966 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_arcexcsch (FUNCARGS) static
Definition at line 973 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_arcexsec (FUNCARGS) static
Definition at line 994 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_arcexsech (FUNCARGS) static
Definition at line 1001 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_arcsec (FUNCARGS) static
Definition at line 830 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_arcsech (FUNCARGS) static
Definition at line 844 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_arcvercos (FUNCARGS) static
Definition at line 893 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_arcvercosh (FUNCARGS) static
Definition at line 900 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_arcversin (FUNCARGS) static
Definition at line 865 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_arcversinh (FUNCARGS) static
Definition at line 872 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_asec (FUNCARGS) static
Definition at line 823 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_asech (FUNCARGS) static
Definition at line 837 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_bit_length (FUNCARGS) static
Definition at line 1171 of file pymathfunc.c.
References ASSERT_ULONGLONG_ARG, bit_length(), ull2int, and ullint.
static PyObject* mathfunc_cos_arcsin (FUNCARGS) static
Definition at line 1025 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, double2float, and squareroot().
static PyObject* mathfunc_cos_arctan (FUNCARGS) static
Definition at line 1032 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, double2float, and squareroot().
static PyObject* mathfunc_cot (FUNCARGS) static
Definition at line 774 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_coth (FUNCARGS) static
Definition at line 767 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_crd (FUNCARGS) static
Definition at line 732 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_csc (FUNCARGS) static
Definition at line 816 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_csch (FUNCARGS) static
Definition at line 809 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_doublefactorial (FUNCARGS) static
Definition at line 600 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, doublefactoriallonglong(), ll2int, and sllint.
static PyObject* mathfunc_excot (FUNCARGS) static
Definition at line 959 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_excoth (FUNCARGS) static
Definition at line 952 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_excsc (FUNCARGS) static
Definition at line 987 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_excsch (FUNCARGS) static
Definition at line 980 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_exsec (FUNCARGS) static
Definition at line 1015 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_exsech (FUNCARGS) static
Definition at line 1008 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_factorial (FUNCARGS) static
Definition at line 593 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, factoriallonglong(), ll2int, and sllint.
static PyObject* mathfunc_fib (FUNCARGS) static
Definition at line 631 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ll2int, and sllint.
static PyObject* mathfunc_float_diff (FUNCARGS) static
Definition at line 1164 of file pymathfunc.c.
References ASSERT_2DOUBLE_ARG, and double2float.
static PyObject* mathfunc_fma (FUNCARGS) static
Definition at line 1138 of file pymathfunc.c.
References ASSERT_3DOUBLE_ARG, and double2float.
static PyObject* mathfunc_fpclassify (FUNCARGS) static
Definition at line 1149 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and int2int.
static PyObject* mathfunc_hacoversin (FUNCARGS) static
Definition at line 928 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_haversin (FUNCARGS) static
Definition at line 921 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_heptagonal_num (FUNCARGS) static
Definition at line 694 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, heptagonal_numlonglong(), ll2int, and sllint.
static PyObject* mathfunc_hexagonal_num (FUNCARGS) static
Definition at line 687 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, hexagonal_numlonglong(), ll2int, and sllint.
static PyObject* mathfunc_iscomposite (FUNCARGS) static
Definition at line 1127 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglongcomposite(), returnbool, and sllint.
static PyObject* mathfunc_isfloatsquare (FUNCARGS) static
Definition at line 1064 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, isdoublesquare(), and returnbool.
static PyObject* mathfunc_isheptagonal (FUNCARGS) static
Definition at line 1087 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglongheptagonal(), returnbool, and sllint.
static PyObject* mathfunc_ishexagonal (FUNCARGS) static
Definition at line 1079 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglonghexagonal(), returnbool, and sllint.
static PyObject* mathfunc_ismersennenumber (FUNCARGS) static
Definition at line 1103 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglongmersennenumber(), returnbool, and sllint.
static PyObject* mathfunc_ismersenneprime (FUNCARGS) static
Definition at line 1111 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglongmersenneprime(), returnbool, and sllint.
static PyObject* mathfunc_ispoweroftwo (FUNCARGS) static
Definition at line 1095 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglongpoweroftwo(), returnbool, and sllint.
static PyObject* mathfunc_isprime (FUNCARGS) static
Definition at line 1119 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglongprime(), returnbool, and sllint.
static PyObject* mathfunc_issquare (FUNCARGS) static
Definition at line 1056 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglongsquare(), returnbool, and sllint.
static PyObject* mathfunc_istriangular (FUNCARGS) static
Definition at line 1071 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ERR_POSITIVE_INT, islonglongtriangular(), returnbool, and sllint.
static PyObject* mathfunc_mersenne_num (FUNCARGS) static
Definition at line 715 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ll2int, mersenne_numlonglong(), and sllint.
static PyObject* mathfunc_pentatope_num (FUNCARGS) static
Definition at line 708 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ll2int, pentatope_numlonglong(), and sllint.
static PyObject* mathfunc_pow2 (FUNCARGS) static
Definition at line 56 of file pymathfunc.c.
static PyObject* mathfunc_pow_ten (FUNCARGS) static
Definition at line 545 of file pymathfunc.c.
References ASSERT_INT_ARG, double2float, and pow_ten().
static PyObject* mathfunc_pow_ten_int (FUNCARGS) static
Definition at line 552 of file pymathfunc.c.
References ASSERT_UINT_ARG, pow_ten_int(), and ull2int.
static PyObject* mathfunc_pow_ten_int_fast (FUNCARGS) static
Definition at line 559 of file pymathfunc.c.
References ASSERT_UINT_ARG, pow_ten_int_fast(), and ull2int.
static PyObject* mathfunc_pow_ten_neg (FUNCARGS) static
Definition at line 573 of file pymathfunc.c.
References ASSERT_INT_ARG, double2float, and pow_ten_neg().
static PyObject* mathfunc_pow_ten_pos (FUNCARGS) static
Definition at line 566 of file pymathfunc.c.
References ASSERT_UINT_ARG, double2float, and pow_ten_pos().
static PyObject* mathfunc_pronic (FUNCARGS) static
Definition at line 624 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ll2int, proniclonglong(), and sllint.
static PyObject* mathfunc_quadfactorial (FUNCARGS) static
Definition at line 607 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ll2int, quadfactoriallonglong(), and sllint.
static PyObject* mathfunc_sec (FUNCARGS) static
Definition at line 858 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_sech (FUNCARGS) static
Definition at line 851 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_sin_arcsec (FUNCARGS) static
Definition at line 1039 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, double2float, and squareroot().
static PyObject* mathfunc_sin_arctan (FUNCARGS) static
Definition at line 1046 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, double2float, and squareroot().
static PyObject* mathfunc_sinpi (FUNCARGS) static
Definition at line 725 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, double2float, and sinpi().
static PyObject* mathfunc_squareroot (FUNCARGS) static
Definition at line 583 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, double2float, and squareroot().
static PyObject* mathfunc_superfactorial (FUNCARGS) static
Definition at line 614 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ll2int, sllint, and superfactoriallonglong().
static PyObject* mathfunc_tetrahedral_num (FUNCARGS) static
Definition at line 701 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ll2int, sllint, and tetrahedral_numlonglong().
static PyObject* mathfunc_triangular_num (FUNCARGS) static
Definition at line 680 of file pymathfunc.c.
References ASSERT_LONGLONG_ARG, ll2int, sllint, and triangular_numlonglong().
static PyObject* mathfunc_vercos (FUNCARGS) static
Definition at line 914 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_vercosh (FUNCARGS) static
Definition at line 907 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_versin (FUNCARGS) static
Definition at line 886 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
static PyObject* mathfunc_versinh (FUNCARGS) static
Definition at line 879 of file pymathfunc.c.
References ASSERT_DOUBLE_ARG, and double2float.
PyModule_AddStringConstant (m , "__author__" , __author__)
PyModule_AddStringConstant (m , "__version__" , __version__)
Variable Documentation
m = PyModule_Create(&module)
Definition at line 520 of file pymathfunc.c.
MODINIT
Initial value:
{
    PyObject *m
Definition at line 518 of file pymathfunc.c.
struct PyModuleDef module static
Initial value:
= {
    PyModuleDef_HEAD_INIT,
    MODNAME,
    module_docstring,
    -1,
    module_methods,
    NULL,
    NULL,
    NULL,
    NULL
}
Definition at line 505 of file pymathfunc.c.