PyBooster: pyphysics.c File Reference
pyphysics.c File Reference
Physics Functions from physics.c.
#include "PY_MACROS.h"
#include "physics.h"
Macros
#define MODINIT PyMODINIT_FUNC PyInit_physics(void)
#define MODNAME "physics"
Functions
MODINIT __attribute__ ((flatten, hot))
if (return m==(PyObject *) NULL)
static PyObject * physics_density (FUNCARGS)
static PyObject * physics_distance (FUNCARGS)
static PyObject * physics_force (FUNCARGS)
static PyObject * physics_impulse (FUNCARGS)
static PyObject * physics_momentum (FUNCARGS)
static PyObject * physics_pressure (FUNCARGS)
static PyObject * physics_speed (FUNCARGS)
PyModule_AddStringConstant (m,"__author__", __author__)
PyModule_AddStringConstant (m,"__version__", __version__)
Variables
m = PyModule_Create(&module)
MODINIT
static struct PyModuleDef module
Detailed Description
Physics Functions from physics.c.
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.21
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Definition in file pyphysics.c.
Macro Definition Documentation
#define MODINIT PyMODINIT_FUNC PyInit_physics(void)
Definition at line 34 of file pyphysics.c.
#define MODNAME "physics"
Definition at line 33 of file pyphysics.c.
Function Documentation
MODINIT __attribute__ ((flatten, hot))
if (return m = = (PyObject *)NULL)
Definition at line 131 of file pyphysics.c.
static PyObject* physics_density (FUNCARGS) static
Definition at line 55 of file pyphysics.c.
static PyObject* physics_distance (FUNCARGS) static
Definition at line 153 of file pyphysics.c.
References ASSERT_2DOUBLE_ARG, double2float, and speed().
static PyObject* physics_force (FUNCARGS) static
Definition at line 174 of file pyphysics.c.
References ASSERT_2DOUBLE_ARG, and double2float.
static PyObject* physics_impulse (FUNCARGS) static
Definition at line 181 of file pyphysics.c.
References ASSERT_2DOUBLE_ARG, double2float, and force().
static PyObject* physics_momentum (FUNCARGS) static
Definition at line 167 of file pyphysics.c.
References ASSERT_2DOUBLE_ARG, and double2float.
static PyObject* physics_pressure (FUNCARGS) static
Definition at line 146 of file pyphysics.c.
References ASSERT_2DOUBLE_ARG, double2float, and force().
static PyObject* physics_speed (FUNCARGS) static
Definition at line 160 of file pyphysics.c.
References ASSERT_2DOUBLE_ARG, distance(), and double2float.
PyModule_AddStringConstant (m , "__author__" , __author__)
PyModule_AddStringConstant (m , "__version__" , __version__)
Variable Documentation
m = PyModule_Create(&module)
Definition at line 124 of file pyphysics.c.
MODINIT
Initial value:
{
    PyObject *m
Definition at line 122 of file pyphysics.c.
struct PyModuleDef module static
Initial value:
= {
    PyModuleDef_HEAD_INIT,
    MODNAME,
    module_docstring,
    -1,
    module_methods,
    NULL,
    NULL,
    NULL,
    NULL
}
Definition at line 109 of file pyphysics.c.