PyBooster: pytools.c File Reference
pytools.c File Reference
Miscellaneous Functions (from tools.c and x86_64_asm_func.c)
#include "PY_MACROS.h"
#include "tools.h"
#include "x86_64_asm_func.h"
Macros
#define MODINIT PyMODINIT_FUNC PyInit_tools(void)
#define MODNAME "tools"
Functions
MODINIT __attribute__ ((flatten, hot))
if (return m==(PyObject *) NULL)
PyModule_AddStringConstant (m,"__author__", __author__)
PyModule_AddStringConstant (m,"__version__", __version__)
static PyObject * tools_CSTD (void)
static PyObject * tools_endianness (void)
static PyObject * tools_getarch (void)
static PyObject * tools_getos (void)
static PyObject * tools_isandroid (void)
static PyObject * tools_isstralnum (FUNCARGS)
static PyObject * tools_isstralpha (FUNCARGS)
static PyObject * tools_isstrgraphical (FUNCARGS)
static PyObject * tools_isstrhex (FUNCARGS)
static PyObject * tools_isstrlowercase (FUNCARGS)
static PyObject * tools_isstrnum (FUNCARGS)
static PyObject * tools_isstrprintable (FUNCARGS)
static PyObject * tools_isstrpunctuation (FUNCARGS)
static PyObject * tools_isstruppercase (FUNCARGS)
static PyObject * tools_isstrwhitespace (FUNCARGS)
static PyObject * tools_lowercasestr (FUNCARGS)
static PyObject * tools_lowercasestr15 (FUNCARGS)
static PyObject * tools_rmgravequote (FUNCARGS)
static PyObject * tools_strreplace (FUNCARGS)
static PyObject * tools_strreplace_once (FUNCARGS)
static PyObject * tools_uppercasestr (FUNCARGS)
Variables
m = PyModule_Create(&module)
MODINIT
static struct PyModuleDef module
Detailed Description
Miscellaneous Functions (from tools.c and x86_64_asm_func.c)
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.21
DESCRIPTION
This is a Python3 module that uses functions from tools.c Various functions that do not fit in other categories. Such functions include string manipulations, file I/O, boolean tests, etc.
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Definition in file pytools.c.
Macro Definition Documentation
#define MODINIT PyMODINIT_FUNC PyInit_tools(void)
Definition at line 40 of file pytools.c.
#define MODNAME "tools"
Definition at line 39 of file pytools.c.
Function Documentation
MODINIT __attribute__ ((flatten, hot))
if (return m = = (PyObject *)NULL)
Definition at line 610 of file pytools.c.
PyModule_AddStringConstant (m , "__author__" , __author__)
PyModule_AddStringConstant (m , "__version__" , __version__)
static PyObject* tools_CSTD (void) static
Definition at line 1676 of file pytools.c.
References __STDC_VERSION__, and long2int.
static PyObject* tools_endianness (void) static
Definition at line 1542 of file pytools.c.
References endianness(), and STR.
static PyObject* tools_getarch (void) static
Definition at line 1550 of file pytools.c.
References STR.
static PyObject* tools_getos (void) static
Definition at line 1583 of file pytools.c.
References STR.
static PyObject* tools_isandroid (void) static
Definition at line 1667 of file pytools.c.
static PyObject* tools_isstralnum (FUNCARGS) static
Definition at line 829 of file pytools.c.
References ASSERT_STRING_ARG, ISALNUM, and strlenx().
static PyObject* tools_isstralpha (FUNCARGS) static
Definition at line 838 of file pytools.c.
References ASSERT_STRING_ARG, ISALPHA, and strlenx().
static PyObject* tools_isstrgraphical (FUNCARGS) static
Definition at line 856 of file pytools.c.
References ASSERT_STRING_ARG, ISGRAPH, and strlenx().
static PyObject* tools_isstrhex (FUNCARGS) static
Definition at line 892 of file pytools.c.
References ASSERT_STRING_ARG, ISXDIGIT, and strlenx().
static PyObject* tools_isstrlowercase (FUNCARGS) static
Definition at line 811 of file pytools.c.
References ASSERT_STRING_ARG, ISLOWERASCII, and strlenx().
static PyObject* tools_isstrnum (FUNCARGS) static
Definition at line 847 of file pytools.c.
References ASSERT_STRING_ARG, ISDIGIT, and strlenx().
static PyObject* tools_isstrprintable (FUNCARGS) static
Definition at line 865 of file pytools.c.
References ASSERT_STRING_ARG, ISPRINT, and strlenx().
static PyObject* tools_isstrpunctuation (FUNCARGS) static
Definition at line 874 of file pytools.c.
References ASSERT_STRING_ARG, ISPUNCT, and strlenx().
static PyObject* tools_isstruppercase (FUNCARGS) static
Definition at line 820 of file pytools.c.
References ASSERT_STRING_ARG, ISUPPERASCII, and strlenx().
static PyObject* tools_isstrwhitespace (FUNCARGS) static
Definition at line 883 of file pytools.c.
References ASSERT_STRING_ARG, ISSPACE, and strlenx().
static PyObject* tools_lowercasestr (FUNCARGS) static
Definition at line 48 of file pytools.c.
static PyObject* tools_lowercasestr15 (FUNCARGS) static
Definition at line 702 of file pytools.c.
References ASSERT_STRING_ARG, and STR.
static PyObject* tools_rmgravequote (FUNCARGS) static
Definition at line 937 of file pytools.c.
References ASSERT_STRING_ARG, rmgravequote(), and STR.
static PyObject* tools_strreplace (FUNCARGS) static
Definition at line 904 of file pytools.c.
References ASSERT_3STRING_ARG, STR, strlenx(), and ulint.
static PyObject* tools_strreplace_once (FUNCARGS) static
Definition at line 930 of file pytools.c.
References ASSERT_3STRING_ARG, STR, and strreplace_once().
static PyObject* tools_uppercasestr (FUNCARGS) static
Definition at line 727 of file pytools.c.
References ASSERT_STRING_ARG, STR, and strlenx().
Variable Documentation
m = PyModule_Create(&module)
Definition at line 603 of file pytools.c.
MODINIT
Initial value:
{
    PyObject *m
Definition at line 601 of file pytools.c.
struct PyModuleDef module static
Initial value:
= {
    PyModuleDef_HEAD_INIT,
    MODNAME,
    module_docstring,
    -1,
    module_methods,
    NULL,
    NULL,
    NULL,
    NULL
}
Definition at line 588 of file pytools.c.