PyBooster: tools.h File Reference
tools.h File Reference
Miscellaneous Functions (header)
#include "MACROS.h"
Functions
void appendfile (const char *__restrict__ filename, uint8_t *data, const size_t datasize) __attribute__((flatten
void appendfilebuf (const char *__restrict__ filename, char *data, const size_t datasize) __attribute__((flatten
size_t bytelen_utf32 (const uint32_t *__restrict__ utf32str) __attribute__((const
int char_in_str (const char *__restrict__ str, const char _char) __attribute__((flatten
long CSTD (void) __attribute__((const))
const char * endianness (void) __attribute__((returns_nonnull))
uint16_t fileadler16 (const char *__restrict__ filename) __attribute__((flatten
uint32_t fileadler32 (const char *__restrict__ filename) __attribute__((flatten
uint64_t fileadler64 (const char *__restrict__ filename) __attribute__((flatten
uint64_t fileantiadler64 (const char *__restrict__ filename) __attribute__((flatten
uint64_t fileantiadler64rev2 (const char *__restrict__ filename) __attribute__((flatten
uint8_t filebitparity64 (const char *__restrict__ filename) __attribute__((flatten
uint32_t filecollier32 (const char *__restrict__ filename) __attribute__((flatten
int fileexists (const char *__restrict__ filename) __attribute__((flatten
uint16_t filefletcher16 (const char *__restrict__ filename) __attribute__((flatten
uint16_t filefletcher16fast (const char *__restrict__ filename) __attribute__((flatten
uint32_t filefletcher32 (const char *__restrict__ filename) __attribute__((flatten
uint32_t filefletcher32fast (const char *__restrict__ filename) __attribute__((flatten
uint64_t filesize64 (const char *__restrict__ filename) __attribute__((flatten
int filewritable (const char *__restrict__ filename) __attribute__((flatten
uint8_t * get_hidden_data_from_file (const char *__restrict__ filename) __attribute__((flatten
size_t get_size_of_hidden_data (const char *__restrict__ filename) __attribute__((flatten
const char * getarch (void) __attribute__((returns_nonnull))
uint8_t * getbinfile (const char *__restrict__ filename) __attribute__((flatten
uint8_t * getbinfile_sizet (const char *__restrict__ filename, const size_t filesize) __attribute__((flatten
const char * getcompilername (void)
const char * getcompilerversion (void) __attribute__((const
char * getfile (const char *__restrict__ filename) __attribute__((flatten
char * getfile_sizet (const char *__restrict__ filename, const size_t filesize) __attribute__((flatten
ulint getfilesize (const char *__restrict__ filename) __attribute__((flatten
size_t getfilesize_t (const char *__restrict__ filename) __attribute__((flatten
const char * getos (void) __attribute__((returns_nonnull))
void hide_data_in_file (const char *__restrict__ filename, const uint8_t *__restrict__ data, const size_t datasize) __attribute__((flatten
void inplace_strsub (char *orig_string, const char *__restrict__ find, const char *__restrict__ sub_with)
int isaix (void) __attribute__((const))
int isalnumx (const int x) __attribute__((const
int isalphax (const int x) __attribute__((const
int isandroid (void) __attribute__((const))
int isasciix (const int x) __attribute__((const
int isblankx (const int x) __attribute__((const
int iscntrl_ascii (const int x) __attribute__((const
int isdigit_ascii (const int x) __attribute__((const
int iseven (const int num) __attribute__((flatten
int isgraph_ascii (const int x) __attribute__((const
int islibelf (void) __attribute__((const))
int islongeven (const long num) __attribute__((flatten
int islongodd (const long num) __attribute__((flatten
int islower_ascii (const int x) __attribute__((const
int isodd (const int num) __attribute__((flatten
int isprintx (const int x) __attribute__((const
int isptr64bit (void) __attribute__((const))
int ispunct_ascii (const int x) __attribute__((const
int isspace_ascii (const int x) __attribute__((const
int isstralnum (const char *__restrict__ str) __attribute__((flatten
int isstralpha (const char *__restrict__ str) __attribute__((flatten
int isstrgraphical (const char *__restrict__ str) __attribute__((flatten
int isstrhex (const char *__restrict__ str) __attribute__((flatten
int isstrlowercase (const char *__restrict__ str) __attribute__((flatten
int isstrnum (const char *__restrict__ str) __attribute__((flatten
int isstrprintable (const char *__restrict__ str) __attribute__((flatten
int isstrpunctuation (const char *__restrict__ str) __attribute__((flatten
int isstruppercase (const char *__restrict__ str) __attribute__((flatten
int isstrwhitespace (const char *__restrict__ str) __attribute__((flatten
int isuint64even (const uint64_t num) __attribute__((flatten
int isuint64odd (const uint64_t num) __attribute__((flatten
int isupper_ascii (const int x) __attribute__((const
int isxdigit_ascii (const int x) __attribute__((const
void lowercasestr (char *__restrict__ str) __attribute__((flatten
void lowercasestrx (char *__restrict__ str, const size_t len) __attribute__((flatten
char * rmgravequote (char *orig_string)
int space_in_str (const char *__restrict__ str) __attribute__((flatten
char * STPCPY (char *__restrict__ dst, const char *__restrict__ src) __attribute__((flatten
char * STPCPYX (char *__restrict__ dst, const char *__restrict__ src, const size_t srclen) __attribute__((flatten
char * STPNCPY (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen) __attribute__((flatten
int str_in_str (const char *__restrict__ str, const char *__restrict__ substr) __attribute__((flatten
char * STRCAT (char *__restrict__ dst, const char *__restrict__ src) __attribute__((flatten
char * STRCATX (char *__restrict__ dst, const char *__restrict__ src, const size_t dstlen, const size_t srclen) __attribute__((flatten
char * STRCPY (char *__restrict__ dst, const char *__restrict__ src) __attribute__((flatten
char * STRCPYX (char *__restrict__ dst, const char *__restrict__ src, const size_t srclen) __attribute__((flatten
char * strdupx (const char *__restrict__ s) __attribute__((flatten
size_t STRLCAT (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen) __attribute__((flatten
size_t STRLCPY (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen) __attribute__((flatten
size_t strlen_utf32 (const uint32_t *__restrict__ utf32str) __attribute__((const
size_t strlenx (const char *__restrict__ str) __attribute__((const
size_t strlenx_uint8 (const uint8_t *__restrict__ str) __attribute__((const
char * STRNCAT (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen) __attribute__((flatten
char * STRNCPY (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen) __attribute__((flatten
char * STRNCPYX (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen, const size_t srclen) __attribute__((flatten
char * strreplace (char *orig_string, const char *find, const char *replace_with)
char * strreplace_once (char *orig_string, const char *find, const char *replace_with)
void strrmquotes (char *line)
int tolowerx (const int x) __attribute__((const
int toupperx (const int x) __attribute__((const
void uppercasestr (char *__restrict__ str) __attribute__((flatten
void uppercasestrx (char *__restrict__ str, const size_t len) __attribute__((flatten
void writefile (const char *__restrict__ filename, uint8_t *data, const size_t filesize) __attribute__((flatten))
void writefilebuf (const char *__restrict__ filename, char *data, const size_t filesize) __attribute__((flatten))
void xorswap (int *__restrict__ x, int *__restrict__ y) __attribute__((nonnull))
void xorswap_sll (sllint *__restrict__ x, sllint *__restrict__ y) __attribute__((nonnull))
Variables
int const
int flatten
char nonnull
const char returns_nonnull
Detailed Description
Miscellaneous Functions (header)
Author
Devyn Collier Johnson Devyn.nosp@m.CJoh.nosp@m.nson@.nosp@m.Gmai.nosp@m.l.com
Copyright
LGPLv3
Version
2016.03.21
DESCRIPTION
Various functions that do not fit in other categories. Such functions include string manipulations, file I/O, boolean tests, etc.
LICENSE
GNU Lesser General Public License v3 Copyright (c) Devyn Collier Johnson, All rights reserved.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3.0 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library.
Definition in file tools.h.
Function Documentation
void appendfile (const char *__restrict__ filename, uint8_t * data, const size_t datasize)
void appendfilebuf (const char *__restrict__ filename, char * data, const size_t datasize)
size_t bytelen_utf32 (const uint32_t *__restrict__ utf32str) const
int char_in_str (const char *__restrict__ str, const char _char)
long CSTD (void) const
const char* endianness (void)
Return the system's endianness
Definition at line 1647 of file tools.c.
References UINT32_C.
Referenced by tools_endianness().
uint16_t fileadler16 (const char *__restrict__ filename)
uint32_t fileadler32 (const char *__restrict__ filename)
uint64_t fileadler64 (const char *__restrict__ filename)
uint64_t fileantiadler64 (const char *__restrict__ filename)
uint64_t fileantiadler64rev2 (const char *__restrict__ filename)
uint8_t filebitparity64 (const char *__restrict__ filename)
uint32_t filecollier32 (const char *__restrict__ filename)
int fileexists (const char *__restrict__ filename)
uint16_t filefletcher16 (const char *__restrict__ filename)
uint16_t filefletcher16fast (const char *__restrict__ filename)
uint32_t filefletcher32 (const char *__restrict__ filename)
uint32_t filefletcher32fast (const char *__restrict__ filename)
uint64_t filesize64 (const char *__restrict__ filename)
int filewritable (const char *__restrict__ filename)
uint8_t* get_hidden_data_from_file (const char *__restrict__ filename)
size_t get_size_of_hidden_data (const char *__restrict__ filename)
const char* getarch (void)
Get the system's architecture type
Definition at line 1528 of file tools.c.
uint8_t* getbinfile (const char *__restrict__ filename)
uint8_t* getbinfile_sizet (const char *__restrict__ filename, const size_t filesize)
const char* getcompilername (void)
Get the name of the compiler that compiled this library
Definition at line 1744 of file tools.c.
const char* getcompilerversion (void) const
char* getfile (const char *__restrict__ filename)
char* getfile_sizet (const char *__restrict__ filename, const size_t filesize)
ulint getfilesize (const char *__restrict__ filename)
size_t getfilesize_t (const char *__restrict__ filename)
const char* getos (void)
Get the system's operating-system name
Definition at line 1562 of file tools.c.
void hide_data_in_file (const char *__restrict__ filename, const uint8_t *__restrict__ data, const size_t datasize)
void inplace_strsub (char * orig_string, const char *__restrict__ find, const char *__restrict__ sub_with)
Find and substitute all occurrences of "find" with "sub_with", inplace
Definition at line 1443 of file tools.c.
References strlenx().
int isaix (void) const
int isalnumx (const int x) const
int isalphax (const int x) const
int isandroid (void) const
int isasciix (const int x) const
int isblankx (const int x) const
int iscntrl_ascii (const int x) const
int isdigit_ascii (const int x) const
int iseven (const int num)
int isgraph_ascii (const int x) const
int islibelf (void) const
int islongeven (const long num)
int islongodd (const long num)
int islower_ascii (const int x) const
int isodd (const int num)
int isprintx (const int x) const
int isptr64bit (void) const
int ispunct_ascii (const int x) const
int isspace_ascii (const int x) const
int isstralnum (const char *__restrict__ str)
int isstralpha (const char *__restrict__ str)
int isstrgraphical (const char *__restrict__ str)
int isstrhex (const char *__restrict__ str)
int isstrlowercase (const char *__restrict__ str)
int isstrnum (const char *__restrict__ str)
int isstrprintable (const char *__restrict__ str)
int isstrpunctuation (const char *__restrict__ str)
int isstruppercase (const char *__restrict__ str)
int isstrwhitespace (const char *__restrict__ str)
int isuint64even (const uint64_t num)
int isuint64odd (const uint64_t num)
int isupper_ascii (const int x) const
int isxdigit_ascii (const int x) const
void lowercasestr (char *__restrict__ str)
void lowercasestrx (char *__restrict__ str, const size_t len)
char* rmgravequote (char * orig_string)
Find and remove grave-quotes (`)
Definition at line 1493 of file tools.c.
References strlenx().
Referenced by tools_rmgravequote().
int space_in_str (const char *__restrict__ str)
char* STPCPY (char *__restrict__ dst, const char *__restrict__ src)
char* STPCPYX (char *__restrict__ dst, const char *__restrict__ src, const size_t srclen)
char* STPNCPY (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen)
int str_in_str (const char *__restrict__ str, const char *__restrict__ substr)
char* STRCAT (char *__restrict__ dst, const char *__restrict__ src)
char* STRCATX (char *__restrict__ dst, const char *__restrict__ src, const size_t dstlen, const size_t srclen)
char* STRCPY (char *__restrict__ dst, const char *__restrict__ src)
char* STRCPYX (char *__restrict__ dst, const char *__restrict__ src, const size_t srclen)
char* strdupx (const char *__restrict__ s)
size_t STRLCAT (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen)
size_t STRLCPY (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen)
size_t strlen_utf32 (const uint32_t *__restrict__ utf32str) const
size_t strlenx (const char *__restrict__ str) const
size_t strlenx_uint8 (const uint8_t *__restrict__ str) const
char* STRNCAT (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen)
char* STRNCPY (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen)
char* STRNCPYX (char *__restrict__ dst, const char *__restrict__ src, const size_t maxlen, const size_t srclen)
char* strreplace (char * orig_string, const char * find, const char * replace_with)
Find and replace all occurrences of "find" with "replace_with"
Definition at line 1454 of file tools.c.
References strlenx(), and ulint.
char* strreplace_once (char * orig_string, const char * find, const char * replace_with)
Replace first occurrence of "find" with "replace_with"
Definition at line 1478 of file tools.c.
References strlenx().
Referenced by tools_strreplace_once().
void strrmquotes (char * line)
Remove quotes from a string inplace
Definition at line 1510 of file tools.c.
References strlenx().
int tolowerx (const int x) const
int toupperx (const int x) const
void uppercasestr (char *__restrict__ str)
void uppercasestrx (char *__restrict__ str, const size_t len)
void writefile (const char *__restrict__ filename, uint8_t * data, const size_t filesize)
Write data to a file; unbuffered
Definition at line 524 of file tools.c.
References FAILED_OPEN_FILE, and UNABLE_TO_WRITE_FILE.
void writefilebuf (const char *__restrict__ filename, char * data, const size_t filesize)
Write data to a file; buffered
Definition at line 537 of file tools.c.
References ALLOC_WRITE_ERROR, FAILED_OPEN_FILE, and UNABLE_TO_WRITE_FILE.
void xorswap (int *__restrict__ x, int *__restrict__ y)
Swap the values of `x` and `y` (xorswap(&x, &y))
Definition at line 1833 of file tools.c.
void xorswap_sll (sllint *__restrict__ x, sllint *__restrict__ y)
Swap the values of `x` and `y` (xorswap_sll(&x, &y))
Definition at line 1841 of file tools.c.
Variable Documentation
int const
Definition at line 189 of file tools.h.
size_t flatten
Definition at line 47 of file tools.h.
int nonnull
Definition at line 66 of file tools.h.
const char returns_nonnull
Definition at line 276 of file tools.h.