.TH <UNTITLED> 5 "{command:date +'%B %d, %Y'}" "Version: VERSION" "CENTER_HEADER"


.SH NAME
<untitled> \- BRIEF_DESCRIPTION


.SH SYNOPSIS
.B \fB<untitled>\fR [\fI OPTION \fR]


.SH DESCRIPTION
<Detailed_Description_1>
.sp
<Detailed_Description_2>


.SH NOTES

<Notes_1>
.sp
<Notes_2>


.SH FILES
.BR <FileName>


.SH SEE ALSO
.BR <PKG_Name>


.SH AUTHOR
<untitled> was developed by {developer} <{mail}>
.br
This manual page was prepared by {developer} <{mail}>
