.TH <UNTITLED> 1 "{command:date +'%B %d, %Y'}" "Version: VERSION" "CENTER_HEADER"


.SH NAME
<untitled> \- BRIEF_DESCRIPTION


.SH SYNOPSIS
.B \fB<untitled>\fR [\fI OPTION \fR]


.SH DESCRIPTION
<Detailed_Description_1>
.sp
<Detailed_Description_2>


.SH OPTIONS

.IP "\fB\-X\fR \fIXXX\fR" 4
.IX Item "-X YYY"
.PD 0
.IP "\fB\-\-XXX=\fR\fIYYY\fR" 4
.IX Item "--XXX=YYY"
.PD
<Option_Description>

.IP "\fB\-X\fR \fIXXX\fR" 4
.IX Item "-X YYY"
.PD 0
.IP "\fB\-\-XXX=\fR\fIYYY\fR" 4
.IX Item "--XXX=YYY"
.PD
<Option_Description>


.SH EXAMPLES
<Example_1>
.sp
<Example_2>


.SH SEE ALSO
.BR <PKG_Name>


.SH BUGS
<Describe_Bugs>


.SH AUTHOR
<untitled> was developed by {developer} <{mail}>
.br
This manual page was prepared by {developer} <{mail}>


.SH COPYRIGHT
<Copyright_Information>
