#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim:fileencoding=utf-8
# @brief Flake8 for Python3


import sys

from re import sub

from flake8.main import main

if __name__ == '__main__':
    sys.argv[0] = sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
