#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim:fileencoding=utf-8
# @brief PEP8 Compliance Checker


import sys

from re import sub as _sub

from pep8 import _main

if __name__ == '__main__':
    sys.argv[0] = _sub(r'(-script\.pyw|\.sh|\.py|\.exe)?$', '', sys.argv[0])
    sys.exit(_main())
