#!/usr/bin/env python2
# -*- coding: utf-8 -*-
# vim:fileencoding=utf-8
# EASY-INSTALL-ENTRY-SCRIPT: 'pip>=1.5.6','console_scripts','pip2'
# @brief Pip for Python2


import sys

from pkg_resources import load_entry_point

__requires__ = 'pip>=1.5.6'

if __name__ == '__main__':
    sys.exit(load_entry_point('pip>=1.5.6', 'console_scripts', 'pip2')())
