#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim:fileencoding=utf-8


USAGE = r"""
Usage: py2dsc-deb [options] distfile
   or: py2dsc-deb --help
where distfile is a *.zip or *.tar.gz built with the sdist command
"""


import stdeb.cli_runner
import sys

def main():
    sys.exit(stdeb.cli_runner.runit(cmd='bdist_deb', usage=USAGE))


if __name__ == '__main__':
    main()
